export const testData = {
  notes: [
    {
      id: '1',
      isPublished: true,
      createdAt: 1476850318.715876,
      lastModified: 1476850318.715876,
      tags: [],
      attachments: [],
      authors: [],
      noteType: 'results',
      prompt: 'The results...',
      title: 'Enter your results',
      body: 'this is about a result',
      class: '',
      session: '',
      discussion: ''
    },
    {
      id: '1',
      isPublished: true,
      createdAt: 1476850318.715876,
      lastModified: 1476850318.715876,
      tags: [],
      attachments: [],
      authors: [],
      noteType: 'results',
      prompt: 'The results...',
      title: 'Enter your results',
      body: 'this is about a result',
      class: '',
      session: '',
      discussion: ''
    },
    {
      id: '1',
      isPublished: true,
      createdAt: 1476850318.715876,
      lastModified: 1476850318.715876,
      tags: [],
      attachments: [],
      authors: [],
      noteType: 'results',
      prompt: 'The results...',
      title: 'Enter your results',
      body: 'this is about a result',
      class: '',
      session: '',
      discussion: ''
    },
    {
      id: '1',
      isPublished: true,
      createdAt: 1476850318.715876,
      lastModified: 1476850318.715876,
      tags: [],
      attachments: [],
      authors: [],
      noteType: 'results',
      prompt: 'The results...',
      title: 'Enter your results',
      body: 'this is about a result',
      class: '',
      session: '',
      discussion: ''
    },
    {
      id: '1',
      isPublished: true,
      createdAt: 1476850318.715876,
      lastModified: 1476850318.715876,
      tags: [],
      attachments: [],
      authors: [],
      noteType: 'results',
      prompt: 'The results...',
      title: 'Enter your results',
      body: 'this is about a result',
      class: '',
      session: '',
      discussion: ''
    },
    {
      id: '1',
      isPublished: true,
      createdAt: 1476850318.715876,
      lastModified: 1476850318.715876,
      tags: [],
      attachments: [],
      authors: [],
      noteType: 'results',
      prompt: 'The results...',
      title: 'Enter your results',
      body: 'this is about a result',
      class: '',
      session: '',
      discussion: ''
    },
    {
      id: '1',
      isPublished: true,
      createdAt: 1476850318.715876,
      lastModified: 1476850318.715876,
      tags: [],
      attachments: [],
      authors: [],
      noteType: 'results',
      prompt: 'The results...',
      title: 'Enter your results',
      body: 'this is about a result',
      class: '',
      session: '',
      discussion: ''
    },
    {
      id: '2',
      isPublished: true,
      createdAt: 1476850318.715876,
      lastModified: 1476850318.715876,
      tags: [],
      attachments: [],
      authors: [],
      noteType: 'hypothesis',
      prompt: 'The hypothesis...',
      title: 'Enter your hypothesis',
      body: 'this is about a hypothesis',
      class: '',
      session: '',
      discussion: ''
    },
    {
      id: '3',
      isPublished: true,
      createdAt: 1476850318.715876,
      lastModified: 1476850318.715876,
      tags: [],
      attachments: [],
      authors: [],
      noteType: 'theory',
      prompt: 'The theory...',
      title: 'Enter your theory',
      body: 'this is about a theory',
      class: '',
      session: '',
      discussion: ''
    },
    {
      id: '4',
      isPublished: true,
      createdAt: 1476850318.715876,
      lastModified: 1476850318.715876,
      tags: [],
      attachments: [],
      authors: [],
      noteType: 'results',
      prompt: 'The results...',
      title: 'Enter your results',
      body: 'this is about a result',
      class: '',
      session: '',
      discussion: ''
    }
  ]
};
