// flow-typed signature: 329c6da22892009b8aecdfa3f17d8334
// flow-typed version: <<STUB>>/ac-autocode_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ac-autocode'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ac-autocode' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ac-autocode/src/ActivityRunner/Editor' {
  declare module.exports: any;
}

declare module 'ac-autocode/src/ActivityRunner/Header' {
  declare module.exports: any;
}

declare module 'ac-autocode/src/ActivityRunner/index' {
  declare module.exports: any;
}

declare module 'ac-autocode/src/ActivityRunner/MakeRunCode/index' {
  declare module.exports: any;
}

declare module 'ac-autocode/src/ActivityRunner/MakeRunCode/Javascript' {
  declare module.exports: any;
}

declare module 'ac-autocode/src/ActivityRunner/MakeRunCode/Python' {
  declare module.exports: any;
}

declare module 'ac-autocode/src/ActivityRunner/Test' {
  declare module.exports: any;
}

declare module 'ac-autocode/src/ActivityRunner/TestPanel' {
  declare module.exports: any;
}

declare module 'ac-autocode/src/config' {
  declare module.exports: any;
}

declare module 'ac-autocode/src/Dashboard' {
  declare module.exports: any;
}

declare module 'ac-autocode/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ac-autocode/src/ActivityRunner/Editor.jsx' {
  declare module.exports: $Exports<'ac-autocode/src/ActivityRunner/Editor'>;
}
declare module 'ac-autocode/src/ActivityRunner/Header.jsx' {
  declare module.exports: $Exports<'ac-autocode/src/ActivityRunner/Header'>;
}
declare module 'ac-autocode/src/ActivityRunner/index.js' {
  declare module.exports: $Exports<'ac-autocode/src/ActivityRunner/index'>;
}
declare module 'ac-autocode/src/ActivityRunner/MakeRunCode/index.js' {
  declare module.exports: $Exports<'ac-autocode/src/ActivityRunner/MakeRunCode/index'>;
}
declare module 'ac-autocode/src/ActivityRunner/MakeRunCode/Javascript.jsx' {
  declare module.exports: $Exports<'ac-autocode/src/ActivityRunner/MakeRunCode/Javascript'>;
}
declare module 'ac-autocode/src/ActivityRunner/MakeRunCode/Python.jsx' {
  declare module.exports: $Exports<'ac-autocode/src/ActivityRunner/MakeRunCode/Python'>;
}
declare module 'ac-autocode/src/ActivityRunner/Test.jsx' {
  declare module.exports: $Exports<'ac-autocode/src/ActivityRunner/Test'>;
}
declare module 'ac-autocode/src/ActivityRunner/TestPanel.jsx' {
  declare module.exports: $Exports<'ac-autocode/src/ActivityRunner/TestPanel'>;
}
declare module 'ac-autocode/src/config.js' {
  declare module.exports: $Exports<'ac-autocode/src/config'>;
}
declare module 'ac-autocode/src/Dashboard.jsx' {
  declare module.exports: $Exports<'ac-autocode/src/Dashboard'>;
}
declare module 'ac-autocode/src/index.js' {
  declare module.exports: $Exports<'ac-autocode/src/index'>;
}
