// flow-typed signature: 4b2b76e3808142d72081bdefaa692ca5
// flow-typed version: <<STUB>>/ac-brainstorm_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ac-brainstorm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ac-brainstorm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ac-brainstorm/src/ActivityRunner' {
  declare module.exports: any;
}

declare module 'ac-brainstorm/src/config' {
  declare module.exports: any;
}

declare module 'ac-brainstorm/src/Dashboard' {
  declare module.exports: any;
}

declare module 'ac-brainstorm/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ac-brainstorm/src/ActivityRunner.jsx' {
  declare module.exports: $Exports<'ac-brainstorm/src/ActivityRunner'>;
}
declare module 'ac-brainstorm/src/config.js' {
  declare module.exports: $Exports<'ac-brainstorm/src/config'>;
}
declare module 'ac-brainstorm/src/Dashboard.jsx' {
  declare module.exports: $Exports<'ac-brainstorm/src/Dashboard'>;
}
declare module 'ac-brainstorm/src/index.js' {
  declare module.exports: $Exports<'ac-brainstorm/src/index'>;
}
