// flow-typed signature: b3697e441644581dda6a963a5c2b7022
// flow-typed version: <<STUB>>/ac-ck-board_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ac-ck-board'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ac-ck-board' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ac-ck-board/src/__tests__/mergeFunction' {
  declare module.exports: any;
}

declare module 'ac-ck-board/src/board' {
  declare module.exports: any;
}

declare module 'ac-ck-board/src/index' {
  declare module.exports: any;
}

declare module 'ac-ck-board/src/meta' {
  declare module.exports: any;
}

declare module 'ac-ck-board/src/obs_container' {
  declare module.exports: any;
}

declare module 'ac-ck-board/src/obs_detail' {
  declare module.exports: any;
}

declare module 'ac-ck-board/src/Quadrants' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ac-ck-board/src/__tests__/mergeFunction.js' {
  declare module.exports: $Exports<'ac-ck-board/src/__tests__/mergeFunction'>;
}
declare module 'ac-ck-board/src/board.js' {
  declare module.exports: $Exports<'ac-ck-board/src/board'>;
}
declare module 'ac-ck-board/src/index.js' {
  declare module.exports: $Exports<'ac-ck-board/src/index'>;
}
declare module 'ac-ck-board/src/meta.js' {
  declare module.exports: $Exports<'ac-ck-board/src/meta'>;
}
declare module 'ac-ck-board/src/obs_container.js' {
  declare module.exports: $Exports<'ac-ck-board/src/obs_container'>;
}
declare module 'ac-ck-board/src/obs_detail.js' {
  declare module.exports: $Exports<'ac-ck-board/src/obs_detail'>;
}
declare module 'ac-ck-board/src/Quadrants.js' {
  declare module.exports: $Exports<'ac-ck-board/src/Quadrants'>;
}
