// flow-typed signature: 232ba83170d1e421936215dc2cee9e7c
// flow-typed version: <<STUB>>/ac-chat_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ac-chat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ac-chat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ac-chat/src/Chat' {
  declare module.exports: any;
}

declare module 'ac-chat/src/Dashboard' {
  declare module.exports: any;
}

declare module 'ac-chat/src/dashboardExample/avion' {
  declare module.exports: any;
}

declare module 'ac-chat/src/index' {
  declare module.exports: any;
}

declare module 'ac-chat/src/TextInput' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ac-chat/src/Chat.jsx' {
  declare module.exports: $Exports<'ac-chat/src/Chat'>;
}
declare module 'ac-chat/src/Dashboard.jsx' {
  declare module.exports: $Exports<'ac-chat/src/Dashboard'>;
}
declare module 'ac-chat/src/dashboardExample/avion.js' {
  declare module.exports: $Exports<'ac-chat/src/dashboardExample/avion'>;
}
declare module 'ac-chat/src/index.js' {
  declare module.exports: $Exports<'ac-chat/src/index'>;
}
declare module 'ac-chat/src/TextInput.jsx' {
  declare module.exports: $Exports<'ac-chat/src/TextInput'>;
}
