// flow-typed signature: f45653cb052ad5c895971703bdc80424
// flow-typed version: <<STUB>>/ac-classifier_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ac-classifier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ac-classifier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ac-classifier/src/__tests__/index' {
  declare module.exports: any;
}

declare module 'ac-classifier/src/Classifier' {
  declare module.exports: any;
}

declare module 'ac-classifier/src/components/ObjectList' {
  declare module.exports: any;
}

declare module 'ac-classifier/src/components/ObjectPanel' {
  declare module.exports: any;
}

declare module 'ac-classifier/src/components/ShortcutPanel' {
  declare module.exports: any;
}

declare module 'ac-classifier/src/index' {
  declare module.exports: any;
}

declare module 'ac-classifier/src/meta' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ac-classifier/src/__tests__/index.js' {
  declare module.exports: $Exports<'ac-classifier/src/__tests__/index'>;
}
declare module 'ac-classifier/src/Classifier.jsx' {
  declare module.exports: $Exports<'ac-classifier/src/Classifier'>;
}
declare module 'ac-classifier/src/components/ObjectList.jsx' {
  declare module.exports: $Exports<'ac-classifier/src/components/ObjectList'>;
}
declare module 'ac-classifier/src/components/ObjectPanel.jsx' {
  declare module.exports: $Exports<'ac-classifier/src/components/ObjectPanel'>;
}
declare module 'ac-classifier/src/components/ShortcutPanel.jsx' {
  declare module.exports: $Exports<'ac-classifier/src/components/ShortcutPanel'>;
}
declare module 'ac-classifier/src/index.js' {
  declare module.exports: $Exports<'ac-classifier/src/index'>;
}
declare module 'ac-classifier/src/meta.js' {
  declare module.exports: $Exports<'ac-classifier/src/meta'>;
}
