// flow-typed signature: ae5c212e2f69867352c897aa375ca8db
// flow-typed version: <<STUB>>/ac-display-social_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ac-display-social'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ac-display-social' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ac-display-social/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ac-display-social/src/index.js' {
  declare module.exports: $Exports<'ac-display-social/src/index'>;
}
