// flow-typed signature: 3caa60e98877f6a01f37ddcb5cc40724
// flow-typed version: <<STUB>>/ac-dual_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ac-dual'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ac-dual' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ac-dual/src/ActivityRunner' {
  declare module.exports: any;
}

declare module 'ac-dual/src/ActivityUtils' {
  declare module.exports: any;
}

declare module 'ac-dual/src/Dashboard' {
  declare module.exports: any;
}

declare module 'ac-dual/src/Game' {
  declare module.exports: any;
}

declare module 'ac-dual/src/index' {
  declare module.exports: any;
}

declare module 'ac-dual/src/Symmetry' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ac-dual/src/ActivityRunner.jsx' {
  declare module.exports: $Exports<'ac-dual/src/ActivityRunner'>;
}
declare module 'ac-dual/src/ActivityUtils.jsx' {
  declare module.exports: $Exports<'ac-dual/src/ActivityUtils'>;
}
declare module 'ac-dual/src/Dashboard.jsx' {
  declare module.exports: $Exports<'ac-dual/src/Dashboard'>;
}
declare module 'ac-dual/src/Game.jsx' {
  declare module.exports: $Exports<'ac-dual/src/Game'>;
}
declare module 'ac-dual/src/index.js' {
  declare module.exports: $Exports<'ac-dual/src/index'>;
}
declare module 'ac-dual/src/Symmetry.jsx' {
  declare module.exports: $Exports<'ac-dual/src/Symmetry'>;
}
