// flow-typed signature: 234bcf0a37e0a531deba214cf23606da
// flow-typed version: <<STUB>>/ac-form_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ac-form'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ac-form' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ac-form/src/config' {
  declare module.exports: any;
}

declare module 'ac-form/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ac-form/src/config.js' {
  declare module.exports: $Exports<'ac-form/src/config'>;
}
declare module 'ac-form/src/index.js' {
  declare module.exports: $Exports<'ac-form/src/index'>;
}
