// flow-typed signature: 9049b539a7b4cd4a5c539464968bdd33
// flow-typed version: <<STUB>>/ac-iframe_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ac-iframe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ac-iframe' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ac-iframe/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ac-iframe/src/index.js' {
  declare module.exports: $Exports<'ac-iframe/src/index'>;
}
