// flow-typed signature: 492328c6a6194240dba70271e1bc0810
// flow-typed version: <<STUB>>/ac-image_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ac-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ac-image' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ac-image/src/ActivityRunner' {
  declare module.exports: any;
}

declare module 'ac-image/src/components/CategoryBox' {
  declare module.exports: any;
}

declare module 'ac-image/src/components/CenteredImg' {
  declare module.exports: any;
}

declare module 'ac-image/src/components/ImageBox' {
  declare module.exports: any;
}

declare module 'ac-image/src/components/ThumbList' {
  declare module.exports: any;
}

declare module 'ac-image/src/components/TopBar' {
  declare module.exports: any;
}

declare module 'ac-image/src/components/UploadBar' {
  declare module.exports: any;
}

declare module 'ac-image/src/components/UploadDragDrop' {
  declare module.exports: any;
}

declare module 'ac-image/src/components/WebcamInterface' {
  declare module.exports: any;
}

declare module 'ac-image/src/components/ZoomView' {
  declare module.exports: any;
}

declare module 'ac-image/src/config' {
  declare module.exports: any;
}

declare module 'ac-image/src/Dashboard' {
  declare module.exports: any;
}

declare module 'ac-image/src/index' {
  declare module.exports: any;
}

declare module 'ac-image/src/meta' {
  declare module.exports: any;
}

declare module 'ac-image/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ac-image/src/ActivityRunner.jsx' {
  declare module.exports: $Exports<'ac-image/src/ActivityRunner'>;
}
declare module 'ac-image/src/components/CategoryBox.jsx' {
  declare module.exports: $Exports<'ac-image/src/components/CategoryBox'>;
}
declare module 'ac-image/src/components/CenteredImg.jsx' {
  declare module.exports: $Exports<'ac-image/src/components/CenteredImg'>;
}
declare module 'ac-image/src/components/ImageBox.jsx' {
  declare module.exports: $Exports<'ac-image/src/components/ImageBox'>;
}
declare module 'ac-image/src/components/ThumbList.jsx' {
  declare module.exports: $Exports<'ac-image/src/components/ThumbList'>;
}
declare module 'ac-image/src/components/TopBar.jsx' {
  declare module.exports: $Exports<'ac-image/src/components/TopBar'>;
}
declare module 'ac-image/src/components/UploadBar.jsx' {
  declare module.exports: $Exports<'ac-image/src/components/UploadBar'>;
}
declare module 'ac-image/src/components/UploadDragDrop.jsx' {
  declare module.exports: $Exports<'ac-image/src/components/UploadDragDrop'>;
}
declare module 'ac-image/src/components/WebcamInterface.jsx' {
  declare module.exports: $Exports<'ac-image/src/components/WebcamInterface'>;
}
declare module 'ac-image/src/components/ZoomView.jsx' {
  declare module.exports: $Exports<'ac-image/src/components/ZoomView'>;
}
declare module 'ac-image/src/config.js' {
  declare module.exports: $Exports<'ac-image/src/config'>;
}
declare module 'ac-image/src/Dashboard.jsx' {
  declare module.exports: $Exports<'ac-image/src/Dashboard'>;
}
declare module 'ac-image/src/index.js' {
  declare module.exports: $Exports<'ac-image/src/index'>;
}
declare module 'ac-image/src/meta.js' {
  declare module.exports: $Exports<'ac-image/src/meta'>;
}
declare module 'ac-image/src/utils.js' {
  declare module.exports: $Exports<'ac-image/src/utils'>;
}
