// flow-typed signature: 805829fd9df143dd3bad894f3a077e6f
// flow-typed version: <<STUB>>/ac-induction_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ac-induction'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ac-induction' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ac-induction/src/__tests__/index' {
  declare module.exports: any;
}

declare module 'ac-induction/src/ActivityRunner' {
  declare module.exports: any;
}

declare module 'ac-induction/src/ArrayFun' {
  declare module.exports: any;
}

declare module 'ac-induction/src/config' {
  declare module.exports: any;
}

declare module 'ac-induction/src/Dashboard' {
  declare module.exports: any;
}

declare module 'ac-induction/src/DashboardComponents' {
  declare module.exports: any;
}

declare module 'ac-induction/src/Definition' {
  declare module.exports: any;
}

declare module 'ac-induction/src/End' {
  declare module.exports: any;
}

declare module 'ac-induction/src/exampleData' {
  declare module.exports: any;
}

declare module 'ac-induction/src/Examples' {
  declare module.exports: any;
}

declare module 'ac-induction/src/ImgBis' {
  declare module.exports: any;
}

declare module 'ac-induction/src/index' {
  declare module.exports: any;
}

declare module 'ac-induction/src/mergeFun' {
  declare module.exports: any;
}

declare module 'ac-induction/src/NavigationBar' {
  declare module.exports: any;
}

declare module 'ac-induction/src/Presentation' {
  declare module.exports: any;
}

declare module 'ac-induction/src/StyledComponents' {
  declare module.exports: any;
}

declare module 'ac-induction/src/TestPart/Correction' {
  declare module.exports: any;
}

declare module 'ac-induction/src/TestPart/ModalSubmit' {
  declare module.exports: any;
}

declare module 'ac-induction/src/TestPart/ResponsePanel' {
  declare module.exports: any;
}

declare module 'ac-induction/src/TestPart/Switch' {
  declare module.exports: any;
}

declare module 'ac-induction/src/TestPart/Test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ac-induction/src/__tests__/index.js' {
  declare module.exports: $Exports<'ac-induction/src/__tests__/index'>;
}
declare module 'ac-induction/src/ActivityRunner.jsx' {
  declare module.exports: $Exports<'ac-induction/src/ActivityRunner'>;
}
declare module 'ac-induction/src/ArrayFun.js' {
  declare module.exports: $Exports<'ac-induction/src/ArrayFun'>;
}
declare module 'ac-induction/src/config.js' {
  declare module.exports: $Exports<'ac-induction/src/config'>;
}
declare module 'ac-induction/src/Dashboard.jsx' {
  declare module.exports: $Exports<'ac-induction/src/Dashboard'>;
}
declare module 'ac-induction/src/DashboardComponents.jsx' {
  declare module.exports: $Exports<'ac-induction/src/DashboardComponents'>;
}
declare module 'ac-induction/src/Definition.jsx' {
  declare module.exports: $Exports<'ac-induction/src/Definition'>;
}
declare module 'ac-induction/src/End.jsx' {
  declare module.exports: $Exports<'ac-induction/src/End'>;
}
declare module 'ac-induction/src/exampleData.js' {
  declare module.exports: $Exports<'ac-induction/src/exampleData'>;
}
declare module 'ac-induction/src/Examples.jsx' {
  declare module.exports: $Exports<'ac-induction/src/Examples'>;
}
declare module 'ac-induction/src/ImgBis.jsx' {
  declare module.exports: $Exports<'ac-induction/src/ImgBis'>;
}
declare module 'ac-induction/src/index.js' {
  declare module.exports: $Exports<'ac-induction/src/index'>;
}
declare module 'ac-induction/src/mergeFun.js' {
  declare module.exports: $Exports<'ac-induction/src/mergeFun'>;
}
declare module 'ac-induction/src/NavigationBar.jsx' {
  declare module.exports: $Exports<'ac-induction/src/NavigationBar'>;
}
declare module 'ac-induction/src/Presentation.jsx' {
  declare module.exports: $Exports<'ac-induction/src/Presentation'>;
}
declare module 'ac-induction/src/StyledComponents.js' {
  declare module.exports: $Exports<'ac-induction/src/StyledComponents'>;
}
declare module 'ac-induction/src/TestPart/Correction.js' {
  declare module.exports: $Exports<'ac-induction/src/TestPart/Correction'>;
}
declare module 'ac-induction/src/TestPart/ModalSubmit.jsx' {
  declare module.exports: $Exports<'ac-induction/src/TestPart/ModalSubmit'>;
}
declare module 'ac-induction/src/TestPart/ResponsePanel.jsx' {
  declare module.exports: $Exports<'ac-induction/src/TestPart/ResponsePanel'>;
}
declare module 'ac-induction/src/TestPart/Switch.jsx' {
  declare module.exports: $Exports<'ac-induction/src/TestPart/Switch'>;
}
declare module 'ac-induction/src/TestPart/Test.jsx' {
  declare module.exports: $Exports<'ac-induction/src/TestPart/Test'>;
}
