// flow-typed signature: f78d7998b7f94adc46cb485a15603c22
// flow-typed version: <<STUB>>/ac-monty_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ac-monty'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ac-monty' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ac-monty/src/ActivityRunner' {
  declare module.exports: any;
}

declare module 'ac-monty/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ac-monty/src/ActivityRunner.jsx' {
  declare module.exports: $Exports<'ac-monty/src/ActivityRunner'>;
}
declare module 'ac-monty/src/index.js' {
  declare module.exports: $Exports<'ac-monty/src/index'>;
}
