// flow-typed signature: 24ed950b8bce820bb1e7ddd775b5a861
// flow-typed version: <<STUB>>/ac-prez_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ac-prez'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ac-prez' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ac-prez/src/AnnotationLayer' {
  declare module.exports: any;
}

declare module 'ac-prez/src/constants' {
  declare module.exports: any;
}

declare module 'ac-prez/src/index' {
  declare module.exports: any;
}

declare module 'ac-prez/src/PDF' {
  declare module.exports: any;
}

declare module 'ac-prez/src/Prez' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ac-prez/src/AnnotationLayer.jsx' {
  declare module.exports: $Exports<'ac-prez/src/AnnotationLayer'>;
}
declare module 'ac-prez/src/constants.js' {
  declare module.exports: $Exports<'ac-prez/src/constants'>;
}
declare module 'ac-prez/src/index.js' {
  declare module.exports: $Exports<'ac-prez/src/index'>;
}
declare module 'ac-prez/src/PDF.jsx' {
  declare module.exports: $Exports<'ac-prez/src/PDF'>;
}
declare module 'ac-prez/src/Prez.jsx' {
  declare module.exports: $Exports<'ac-prez/src/Prez'>;
}
