// flow-typed signature: a71434b924af7887e8291974e3970634
// flow-typed version: <<STUB>>/ac-prox_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ac-prox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ac-prox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ac-prox/src/ActivityRunner' {
  declare module.exports: any;
}

declare module 'ac-prox/src/dashboard' {
  declare module.exports: any;
}

declare module 'ac-prox/src/GroupPanel' {
  declare module.exports: any;
}

declare module 'ac-prox/src/index' {
  declare module.exports: any;
}

declare module 'ac-prox/src/NoGroupPanel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ac-prox/src/ActivityRunner.jsx' {
  declare module.exports: $Exports<'ac-prox/src/ActivityRunner'>;
}
declare module 'ac-prox/src/dashboard.js' {
  declare module.exports: $Exports<'ac-prox/src/dashboard'>;
}
declare module 'ac-prox/src/GroupPanel.jsx' {
  declare module.exports: $Exports<'ac-prox/src/GroupPanel'>;
}
declare module 'ac-prox/src/index.js' {
  declare module.exports: $Exports<'ac-prox/src/index'>;
}
declare module 'ac-prox/src/NoGroupPanel.jsx' {
  declare module.exports: $Exports<'ac-prox/src/NoGroupPanel'>;
}
