// flow-typed signature: fb59635e08a248de96797485fafcf964
// flow-typed version: <<STUB>>/ac-quiz_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ac-quiz'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ac-quiz' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ac-quiz/src/__tests__/index' {
  declare module.exports: any;
}

declare module 'ac-quiz/src/ActivityRunner/index' {
  declare module.exports: any;
}

declare module 'ac-quiz/src/ActivityRunner/Justification' {
  declare module.exports: any;
}

declare module 'ac-quiz/src/ActivityRunner/Question' {
  declare module.exports: any;
}

declare module 'ac-quiz/src/ActivityRunner/Quiz' {
  declare module.exports: any;
}

declare module 'ac-quiz/src/ActivityRunner/Widget' {
  declare module.exports: any;
}

declare module 'ac-quiz/src/config' {
  declare module.exports: any;
}

declare module 'ac-quiz/src/Dashboard/CountDashboard' {
  declare module.exports: any;
}

declare module 'ac-quiz/src/Dashboard/index' {
  declare module.exports: any;
}

declare module 'ac-quiz/src/Dashboard/JustificationDashboard' {
  declare module.exports: any;
}

declare module 'ac-quiz/src/index' {
  declare module.exports: any;
}

declare module 'ac-quiz/src/meta' {
  declare module.exports: any;
}

declare module 'ac-quiz/src/rtQ' {
  declare module.exports: any;
}

declare module 'ac-quiz/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ac-quiz/src/__tests__/index.js' {
  declare module.exports: $Exports<'ac-quiz/src/__tests__/index'>;
}
declare module 'ac-quiz/src/ActivityRunner/index.js' {
  declare module.exports: $Exports<'ac-quiz/src/ActivityRunner/index'>;
}
declare module 'ac-quiz/src/ActivityRunner/Justification.jsx' {
  declare module.exports: $Exports<'ac-quiz/src/ActivityRunner/Justification'>;
}
declare module 'ac-quiz/src/ActivityRunner/Question.jsx' {
  declare module.exports: $Exports<'ac-quiz/src/ActivityRunner/Question'>;
}
declare module 'ac-quiz/src/ActivityRunner/Quiz.jsx' {
  declare module.exports: $Exports<'ac-quiz/src/ActivityRunner/Quiz'>;
}
declare module 'ac-quiz/src/ActivityRunner/Widget.jsx' {
  declare module.exports: $Exports<'ac-quiz/src/ActivityRunner/Widget'>;
}
declare module 'ac-quiz/src/config.js' {
  declare module.exports: $Exports<'ac-quiz/src/config'>;
}
declare module 'ac-quiz/src/Dashboard/CountDashboard.jsx' {
  declare module.exports: $Exports<'ac-quiz/src/Dashboard/CountDashboard'>;
}
declare module 'ac-quiz/src/Dashboard/index.js' {
  declare module.exports: $Exports<'ac-quiz/src/Dashboard/index'>;
}
declare module 'ac-quiz/src/Dashboard/JustificationDashboard.jsx' {
  declare module.exports: $Exports<'ac-quiz/src/Dashboard/JustificationDashboard'>;
}
declare module 'ac-quiz/src/index.js' {
  declare module.exports: $Exports<'ac-quiz/src/index'>;
}
declare module 'ac-quiz/src/meta.js' {
  declare module.exports: $Exports<'ac-quiz/src/meta'>;
}
declare module 'ac-quiz/src/rtQ.js' {
  declare module.exports: $Exports<'ac-quiz/src/rtQ'>;
}
declare module 'ac-quiz/src/utils.js' {
  declare module.exports: $Exports<'ac-quiz/src/utils'>;
}
