// flow-typed signature: 62901aa5c3731ebe6fc2ad8b7a7beec0
// flow-typed version: <<STUB>>/ac-ranking_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ac-ranking'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ac-ranking' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ac-ranking/src/ActivityRunner/AddAnswer' {
  declare module.exports: any;
}

declare module 'ac-ranking/src/ActivityRunner/Answer' {
  declare module.exports: any;
}

declare module 'ac-ranking/src/ActivityRunner/AnswerList' {
  declare module.exports: any;
}

declare module 'ac-ranking/src/ActivityRunner/index' {
  declare module.exports: any;
}

declare module 'ac-ranking/src/ActivityRunner/Justification' {
  declare module.exports: any;
}

declare module 'ac-ranking/src/config' {
  declare module.exports: any;
}

declare module 'ac-ranking/src/Dashboard' {
  declare module.exports: any;
}

declare module 'ac-ranking/src/index' {
  declare module.exports: any;
}

declare module 'ac-ranking/src/meta' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ac-ranking/src/ActivityRunner/AddAnswer.jsx' {
  declare module.exports: $Exports<'ac-ranking/src/ActivityRunner/AddAnswer'>;
}
declare module 'ac-ranking/src/ActivityRunner/Answer.jsx' {
  declare module.exports: $Exports<'ac-ranking/src/ActivityRunner/Answer'>;
}
declare module 'ac-ranking/src/ActivityRunner/AnswerList.jsx' {
  declare module.exports: $Exports<'ac-ranking/src/ActivityRunner/AnswerList'>;
}
declare module 'ac-ranking/src/ActivityRunner/index.js' {
  declare module.exports: $Exports<'ac-ranking/src/ActivityRunner/index'>;
}
declare module 'ac-ranking/src/ActivityRunner/Justification.jsx' {
  declare module.exports: $Exports<'ac-ranking/src/ActivityRunner/Justification'>;
}
declare module 'ac-ranking/src/config.js' {
  declare module.exports: $Exports<'ac-ranking/src/config'>;
}
declare module 'ac-ranking/src/Dashboard.jsx' {
  declare module.exports: $Exports<'ac-ranking/src/Dashboard'>;
}
declare module 'ac-ranking/src/index.js' {
  declare module.exports: $Exports<'ac-ranking/src/index'>;
}
declare module 'ac-ranking/src/meta.js' {
  declare module.exports: $Exports<'ac-ranking/src/meta'>;
}
