// flow-typed signature: 376b66dd7c1439630d1b7dedcfb561a9
// flow-typed version: <<STUB>>/ac-stroop_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ac-stroop'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ac-stroop' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ac-stroop/src/__tests__/mergeLog' {
  declare module.exports: any;
}

declare module 'ac-stroop/src/ActivityRunner' {
  declare module.exports: any;
}

declare module 'ac-stroop/src/Dashboard' {
  declare module.exports: any;
}

declare module 'ac-stroop/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ac-stroop/src/__tests__/mergeLog.js' {
  declare module.exports: $Exports<'ac-stroop/src/__tests__/mergeLog'>;
}
declare module 'ac-stroop/src/ActivityRunner.jsx' {
  declare module.exports: $Exports<'ac-stroop/src/ActivityRunner'>;
}
declare module 'ac-stroop/src/Dashboard.jsx' {
  declare module.exports: $Exports<'ac-stroop/src/Dashboard'>;
}
declare module 'ac-stroop/src/index.js' {
  declare module.exports: $Exports<'ac-stroop/src/index'>;
}
