// flow-typed signature: d11085637762a3ef88dbe043eb67850c
// flow-typed version: <<STUB>>/ac-textarea_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ac-textarea'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ac-textarea' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ac-textarea/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ac-textarea/src/index.js' {
  declare module.exports: $Exports<'ac-textarea/src/index'>;
}
