// flow-typed signature: 2a29f69750a3b1d535b77a2f69230429
// flow-typed version: <<STUB>>/ac-timedQuiz_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ac-timedQuiz'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ac-timedQuiz' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ac-timedQuiz/src/ActivityRunner' {
  declare module.exports: any;
}

declare module 'ac-timedQuiz/src/config' {
  declare module.exports: any;
}

declare module 'ac-timedQuiz/src/Dashboard' {
  declare module.exports: any;
}

declare module 'ac-timedQuiz/src/index' {
  declare module.exports: any;
}

declare module 'ac-timedQuiz/src/meta' {
  declare module.exports: any;
}

declare module 'ac-timedQuiz/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ac-timedQuiz/src/ActivityRunner.jsx' {
  declare module.exports: $Exports<'ac-timedQuiz/src/ActivityRunner'>;
}
declare module 'ac-timedQuiz/src/config.js' {
  declare module.exports: $Exports<'ac-timedQuiz/src/config'>;
}
declare module 'ac-timedQuiz/src/Dashboard.jsx' {
  declare module.exports: $Exports<'ac-timedQuiz/src/Dashboard'>;
}
declare module 'ac-timedQuiz/src/index.js' {
  declare module.exports: $Exports<'ac-timedQuiz/src/index'>;
}
declare module 'ac-timedQuiz/src/meta.js' {
  declare module.exports: $Exports<'ac-timedQuiz/src/meta'>;
}
declare module 'ac-timedQuiz/src/utils.js' {
  declare module.exports: $Exports<'ac-timedQuiz/src/utils'>;
}
