// flow-typed signature: 51e3757023ed25b406538db546262860
// flow-typed version: <<STUB>>/ac-train_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ac-train'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ac-train' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ac-train/src/ActivityRunner' {
  declare module.exports: any;
}

declare module 'ac-train/src/ActivityUtils' {
  declare module.exports: any;
}

declare module 'ac-train/src/Dashboards/index' {
  declare module.exports: any;
}

declare module 'ac-train/src/Dashboards/MeanPerInterface' {
  declare module.exports: any;
}

declare module 'ac-train/src/Dashboards/MeanPerTryForEachInterface' {
  declare module.exports: any;
}

declare module 'ac-train/src/Dashboards/MeanThroughOutStudy' {
  declare module.exports: any;
}

declare module 'ac-train/src/Dashboards/utils' {
  declare module.exports: any;
}

declare module 'ac-train/src/Guidelines' {
  declare module.exports: any;
}

declare module 'ac-train/src/index' {
  declare module.exports: any;
}

declare module 'ac-train/src/Interface' {
  declare module.exports: any;
}

declare module 'ac-train/src/Interfaces/Actions' {
  declare module.exports: any;
}

declare module 'ac-train/src/Interfaces/Command' {
  declare module.exports: any;
}

declare module 'ac-train/src/Interfaces/DragDrop/Box' {
  declare module.exports: any;
}

declare module 'ac-train/src/Interfaces/DragDrop/DropElements' {
  declare module.exports: any;
}

declare module 'ac-train/src/Interfaces/DragDrop/index' {
  declare module.exports: any;
}

declare module 'ac-train/src/Interfaces/DragDrop/ItemTypes' {
  declare module.exports: any;
}

declare module 'ac-train/src/Interfaces/Form' {
  declare module.exports: any;
}

declare module 'ac-train/src/Interfaces/Help' {
  declare module.exports: any;
}

declare module 'ac-train/src/Interfaces/index' {
  declare module.exports: any;
}

declare module 'ac-train/src/Interfaces/MapInterface/FromToInputs' {
  declare module.exports: any;
}

declare module 'ac-train/src/Interfaces/MapInterface/index' {
  declare module.exports: any;
}

declare module 'ac-train/src/Interfaces/MapInterface/RadioGroupElements' {
  declare module.exports: any;
}

declare module 'ac-train/src/Interfaces/MapInterface/SwissMap' {
  declare module.exports: any;
}

declare module 'ac-train/src/TicketStatus' {
  declare module.exports: any;
}

declare module 'ac-train/src/Timer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ac-train/src/ActivityRunner.jsx' {
  declare module.exports: $Exports<'ac-train/src/ActivityRunner'>;
}
declare module 'ac-train/src/ActivityUtils.jsx' {
  declare module.exports: $Exports<'ac-train/src/ActivityUtils'>;
}
declare module 'ac-train/src/Dashboards/index.jsx' {
  declare module.exports: $Exports<'ac-train/src/Dashboards/index'>;
}
declare module 'ac-train/src/Dashboards/MeanPerInterface.jsx' {
  declare module.exports: $Exports<'ac-train/src/Dashboards/MeanPerInterface'>;
}
declare module 'ac-train/src/Dashboards/MeanPerTryForEachInterface.jsx' {
  declare module.exports: $Exports<'ac-train/src/Dashboards/MeanPerTryForEachInterface'>;
}
declare module 'ac-train/src/Dashboards/MeanThroughOutStudy.jsx' {
  declare module.exports: $Exports<'ac-train/src/Dashboards/MeanThroughOutStudy'>;
}
declare module 'ac-train/src/Dashboards/utils.js' {
  declare module.exports: $Exports<'ac-train/src/Dashboards/utils'>;
}
declare module 'ac-train/src/Guidelines.jsx' {
  declare module.exports: $Exports<'ac-train/src/Guidelines'>;
}
declare module 'ac-train/src/index.js' {
  declare module.exports: $Exports<'ac-train/src/index'>;
}
declare module 'ac-train/src/Interface.jsx' {
  declare module.exports: $Exports<'ac-train/src/Interface'>;
}
declare module 'ac-train/src/Interfaces/Actions.jsx' {
  declare module.exports: $Exports<'ac-train/src/Interfaces/Actions'>;
}
declare module 'ac-train/src/Interfaces/Command.jsx' {
  declare module.exports: $Exports<'ac-train/src/Interfaces/Command'>;
}
declare module 'ac-train/src/Interfaces/DragDrop/Box.jsx' {
  declare module.exports: $Exports<'ac-train/src/Interfaces/DragDrop/Box'>;
}
declare module 'ac-train/src/Interfaces/DragDrop/DropElements.jsx' {
  declare module.exports: $Exports<'ac-train/src/Interfaces/DragDrop/DropElements'>;
}
declare module 'ac-train/src/Interfaces/DragDrop/index.jsx' {
  declare module.exports: $Exports<'ac-train/src/Interfaces/DragDrop/index'>;
}
declare module 'ac-train/src/Interfaces/DragDrop/ItemTypes.js' {
  declare module.exports: $Exports<'ac-train/src/Interfaces/DragDrop/ItemTypes'>;
}
declare module 'ac-train/src/Interfaces/Form.jsx' {
  declare module.exports: $Exports<'ac-train/src/Interfaces/Form'>;
}
declare module 'ac-train/src/Interfaces/Help.jsx' {
  declare module.exports: $Exports<'ac-train/src/Interfaces/Help'>;
}
declare module 'ac-train/src/Interfaces/index.js' {
  declare module.exports: $Exports<'ac-train/src/Interfaces/index'>;
}
declare module 'ac-train/src/Interfaces/MapInterface/FromToInputs.jsx' {
  declare module.exports: $Exports<'ac-train/src/Interfaces/MapInterface/FromToInputs'>;
}
declare module 'ac-train/src/Interfaces/MapInterface/index.jsx' {
  declare module.exports: $Exports<'ac-train/src/Interfaces/MapInterface/index'>;
}
declare module 'ac-train/src/Interfaces/MapInterface/RadioGroupElements.jsx' {
  declare module.exports: $Exports<'ac-train/src/Interfaces/MapInterface/RadioGroupElements'>;
}
declare module 'ac-train/src/Interfaces/MapInterface/SwissMap.jsx' {
  declare module.exports: $Exports<'ac-train/src/Interfaces/MapInterface/SwissMap'>;
}
declare module 'ac-train/src/TicketStatus.jsx' {
  declare module.exports: $Exports<'ac-train/src/TicketStatus'>;
}
declare module 'ac-train/src/Timer.jsx' {
  declare module.exports: $Exports<'ac-train/src/Timer'>;
}
