// flow-typed signature: 3f5929a3f10bbcc6b21a1713af4f7bbb
// flow-typed version: <<STUB>>/ac-uploader_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ac-uploader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ac-uploader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ac-uploader/src/ActivityRunner' {
  declare module.exports: any;
}

declare module 'ac-uploader/src/index' {
  declare module.exports: any;
}

declare module 'ac-uploader/src/List' {
  declare module.exports: any;
}

declare module 'ac-uploader/src/Presentation' {
  declare module.exports: any;
}

declare module 'ac-uploader/src/UploadPanel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ac-uploader/src/ActivityRunner.jsx' {
  declare module.exports: $Exports<'ac-uploader/src/ActivityRunner'>;
}
declare module 'ac-uploader/src/index.js' {
  declare module.exports: $Exports<'ac-uploader/src/index'>;
}
declare module 'ac-uploader/src/List.jsx' {
  declare module.exports: $Exports<'ac-uploader/src/List'>;
}
declare module 'ac-uploader/src/Presentation.jsx' {
  declare module.exports: $Exports<'ac-uploader/src/Presentation'>;
}
declare module 'ac-uploader/src/UploadPanel.jsx' {
  declare module.exports: $Exports<'ac-uploader/src/UploadPanel'>;
}
