// flow-typed signature: dbcbd50fb39187b8943c28b61557f1b4
// flow-typed version: <<STUB>>/ac-video_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ac-video'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ac-video' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ac-video/src/dashboard' {
  declare module.exports: any;
}

declare module 'ac-video/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ac-video/src/dashboard.js' {
  declare module.exports: $Exports<'ac-video/src/dashboard'>;
}
declare module 'ac-video/src/index.js' {
  declare module.exports: $Exports<'ac-video/src/index'>;
}
