// flow-typed signature: 6676750413e2711f39759f9208cd04e3
// flow-typed version: <<STUB>>/babel-plugin-captains-log_v^1.1.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-captains-log'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-captains-log' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-captains-log/dist/__fixtures__/method-check/code' {
  declare module.exports: any;
}

declare module 'babel-plugin-captains-log/dist/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-captains-log/dist/utils/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-captains-log/dist/utils/pluginOptions' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-captains-log/dist/__fixtures__/method-check/code.js' {
  declare module.exports: $Exports<'babel-plugin-captains-log/dist/__fixtures__/method-check/code'>;
}
declare module 'babel-plugin-captains-log/dist/index.js' {
  declare module.exports: $Exports<'babel-plugin-captains-log/dist/index'>;
}
declare module 'babel-plugin-captains-log/dist/utils/index.js' {
  declare module.exports: $Exports<'babel-plugin-captains-log/dist/utils/index'>;
}
declare module 'babel-plugin-captains-log/dist/utils/pluginOptions.js' {
  declare module.exports: $Exports<'babel-plugin-captains-log/dist/utils/pluginOptions'>;
}
