// flow-typed signature: ac132d492f4fdcc14294e659f62d07e4
// flow-typed version: <<STUB>>/babel-bridge_v^1.12.11/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-bridge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-bridge' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-bridge/build/index' {
  declare module.exports: any;
}

declare module 'babel-bridge/register' {
  declare module.exports: any;
}

declare module 'babel-bridge/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-bridge/build/index.js' {
  declare module.exports: $Exports<'babel-bridge/build/index'>;
}
declare module 'babel-bridge/index' {
  declare module.exports: $Exports<'babel-bridge'>;
}
declare module 'babel-bridge/index.js' {
  declare module.exports: $Exports<'babel-bridge'>;
}
declare module 'babel-bridge/register.js' {
  declare module.exports: $Exports<'babel-bridge/register'>;
}
declare module 'babel-bridge/webpack.config.js' {
  declare module.exports: $Exports<'babel-bridge/webpack.config'>;
}
