// flow-typed signature: 99a839dad745f463b60b997efdbacd44
// flow-typed version: <<STUB>>/bcrypt_v^2.0.1/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bcrypt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bcrypt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bcrypt/bcrypt' {
  declare module.exports: any;
}

declare module 'bcrypt/examples/async_compare' {
  declare module.exports: any;
}

declare module 'bcrypt/examples/forever_gen_salt' {
  declare module.exports: any;
}

declare module 'bcrypt/promises' {
  declare module.exports: any;
}

declare module 'bcrypt/test/async' {
  declare module.exports: any;
}

declare module 'bcrypt/test/implementation' {
  declare module.exports: any;
}

declare module 'bcrypt/test/promise' {
  declare module.exports: any;
}

declare module 'bcrypt/test/repetitions' {
  declare module.exports: any;
}

declare module 'bcrypt/test/sync' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bcrypt/bcrypt.js' {
  declare module.exports: $Exports<'bcrypt/bcrypt'>;
}
declare module 'bcrypt/examples/async_compare.js' {
  declare module.exports: $Exports<'bcrypt/examples/async_compare'>;
}
declare module 'bcrypt/examples/forever_gen_salt.js' {
  declare module.exports: $Exports<'bcrypt/examples/forever_gen_salt'>;
}
declare module 'bcrypt/promises.js' {
  declare module.exports: $Exports<'bcrypt/promises'>;
}
declare module 'bcrypt/test/async.js' {
  declare module.exports: $Exports<'bcrypt/test/async'>;
}
declare module 'bcrypt/test/implementation.js' {
  declare module.exports: $Exports<'bcrypt/test/implementation'>;
}
declare module 'bcrypt/test/promise.js' {
  declare module.exports: $Exports<'bcrypt/test/promise'>;
}
declare module 'bcrypt/test/repetitions.js' {
  declare module.exports: $Exports<'bcrypt/test/repetitions'>;
}
declare module 'bcrypt/test/sync.js' {
  declare module.exports: $Exports<'bcrypt/test/sync'>;
}
