// flow-typed signature: 7f2fa5a46a61b294519b0dfe031836a4
// flow-typed version: <<STUB>>/fastlint_v^1.1.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fastlint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fastlint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'fastlint/index' {
  declare module.exports: $Exports<'fastlint'>;
}
declare module 'fastlint/index.js' {
  declare module.exports: $Exports<'fastlint'>;
}
