// flow-typed signature: 005c9fffefd5524d9b17a7a0bd25b75d
// flow-typed version: <<STUB>>/file-dialog_v^0.0.7/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'file-dialog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'file-dialog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'file-dialog/file-dialog.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'file-dialog/file-dialog.min.js' {
  declare module.exports: $Exports<'file-dialog/file-dialog.min'>;
}
declare module 'file-dialog/index' {
  declare module.exports: $Exports<'file-dialog'>;
}
declare module 'file-dialog/index.js' {
  declare module.exports: $Exports<'file-dialog'>;
}
