// flow-typed signature: 2cd5721720faee52140de4b310bdf900
// flow-typed version: <<STUB>>/frog-utils_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'frog-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'frog-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'frog-utils/src/__tests__/cleanEmptyCols' {
  declare module.exports: any;
}

declare module 'frog-utils/src/__tests__/dataStructureTools' {
  declare module.exports: any;
}

declare module 'frog-utils/src/__tests__/generateReactiveFn' {
  declare module.exports: any;
}

declare module 'frog-utils/src/__tests__/index' {
  declare module.exports: any;
}

declare module 'frog-utils/src/__tests__/socStructTools' {
  declare module.exports: any;
}

declare module 'frog-utils/src/ActivityComponents/react-spreadsheet-component/cell' {
  declare module.exports: any;
}

declare module 'frog-utils/src/ActivityComponents/react-spreadsheet-component/dispatcher' {
  declare module.exports: any;
}

declare module 'frog-utils/src/ActivityComponents/react-spreadsheet-component/helpers' {
  declare module.exports: any;
}

declare module 'frog-utils/src/ActivityComponents/react-spreadsheet-component/row' {
  declare module.exports: any;
}

declare module 'frog-utils/src/ActivityComponents/react-spreadsheet-component/spreadsheet' {
  declare module.exports: any;
}

declare module 'frog-utils/src/ActivityComponents/TableView' {
  declare module.exports: any;
}

declare module 'frog-utils/src/ActivityComponents/TreeView' {
  declare module.exports: any;
}

declare module 'frog-utils/src/cleanEmptyCols' {
  declare module.exports: any;
}

declare module 'frog-utils/src/colorRange' {
  declare module.exports: any;
}

declare module 'frog-utils/src/DashboardComponents/CountChart' {
  declare module.exports: any;
}

declare module 'frog-utils/src/dashboards/coordinates' {
  declare module.exports: any;
}

declare module 'frog-utils/src/dashboards/leaderboard' {
  declare module.exports: any;
}

declare module 'frog-utils/src/dashboards/progress' {
  declare module.exports: any;
}

declare module 'frog-utils/src/dataStructureTools' {
  declare module.exports: any;
}

declare module 'frog-utils/src/EnhancedForm' {
  declare module.exports: any;
}

declare module 'frog-utils/src/enhancedFormUtils' {
  declare module.exports: any;
}

declare module 'frog-utils/src/generateReactiveFn' {
  declare module.exports: any;
}

declare module 'frog-utils/src/generateReactiveMem' {
  declare module.exports: any;
}

declare module 'frog-utils/src/highlightSubstring' {
  declare module.exports: any;
}

declare module 'frog-utils/src/ImageReload' {
  declare module.exports: any;
}

declare module 'frog-utils/src/index' {
  declare module.exports: any;
}

declare module 'frog-utils/src/msToString' {
  declare module.exports: any;
}

declare module 'frog-utils/src/ReactiveText' {
  declare module.exports: any;
}

declare module 'frog-utils/src/renderHTML' {
  declare module.exports: any;
}

declare module 'frog-utils/src/resizeDataURL' {
  declare module.exports: any;
}

declare module 'frog-utils/src/socstructTools' {
  declare module.exports: any;
}

declare module 'frog-utils/src/strfTime' {
  declare module.exports: any;
}

declare module 'frog-utils/src/TextInput' {
  declare module.exports: any;
}

declare module 'frog-utils/src/TimedComponent' {
  declare module.exports: any;
}

declare module 'frog-utils/src/types' {
  declare module.exports: any;
}

declare module 'frog-utils/src/unrollProducts' {
  declare module.exports: any;
}

declare module 'frog-utils/src/URLtoFile' {
  declare module.exports: any;
}

declare module 'frog-utils/src/withDragDropContext' {
  declare module.exports: any;
}

// Filename aliases
declare module 'frog-utils/src/__tests__/cleanEmptyCols.js' {
  declare module.exports: $Exports<'frog-utils/src/__tests__/cleanEmptyCols'>;
}
declare module 'frog-utils/src/__tests__/dataStructureTools.js' {
  declare module.exports: $Exports<'frog-utils/src/__tests__/dataStructureTools'>;
}
declare module 'frog-utils/src/__tests__/generateReactiveFn.js' {
  declare module.exports: $Exports<'frog-utils/src/__tests__/generateReactiveFn'>;
}
declare module 'frog-utils/src/__tests__/index.js' {
  declare module.exports: $Exports<'frog-utils/src/__tests__/index'>;
}
declare module 'frog-utils/src/__tests__/socStructTools.js' {
  declare module.exports: $Exports<'frog-utils/src/__tests__/socStructTools'>;
}
declare module 'frog-utils/src/ActivityComponents/react-spreadsheet-component/cell.js' {
  declare module.exports: $Exports<'frog-utils/src/ActivityComponents/react-spreadsheet-component/cell'>;
}
declare module 'frog-utils/src/ActivityComponents/react-spreadsheet-component/dispatcher.js' {
  declare module.exports: $Exports<'frog-utils/src/ActivityComponents/react-spreadsheet-component/dispatcher'>;
}
declare module 'frog-utils/src/ActivityComponents/react-spreadsheet-component/helpers.js' {
  declare module.exports: $Exports<'frog-utils/src/ActivityComponents/react-spreadsheet-component/helpers'>;
}
declare module 'frog-utils/src/ActivityComponents/react-spreadsheet-component/row.js' {
  declare module.exports: $Exports<'frog-utils/src/ActivityComponents/react-spreadsheet-component/row'>;
}
declare module 'frog-utils/src/ActivityComponents/react-spreadsheet-component/spreadsheet.js' {
  declare module.exports: $Exports<'frog-utils/src/ActivityComponents/react-spreadsheet-component/spreadsheet'>;
}
declare module 'frog-utils/src/ActivityComponents/TableView.jsx' {
  declare module.exports: $Exports<'frog-utils/src/ActivityComponents/TableView'>;
}
declare module 'frog-utils/src/ActivityComponents/TreeView.jsx' {
  declare module.exports: $Exports<'frog-utils/src/ActivityComponents/TreeView'>;
}
declare module 'frog-utils/src/cleanEmptyCols.js' {
  declare module.exports: $Exports<'frog-utils/src/cleanEmptyCols'>;
}
declare module 'frog-utils/src/colorRange.js' {
  declare module.exports: $Exports<'frog-utils/src/colorRange'>;
}
declare module 'frog-utils/src/DashboardComponents/CountChart.jsx' {
  declare module.exports: $Exports<'frog-utils/src/DashboardComponents/CountChart'>;
}
declare module 'frog-utils/src/dashboards/coordinates.js' {
  declare module.exports: $Exports<'frog-utils/src/dashboards/coordinates'>;
}
declare module 'frog-utils/src/dashboards/leaderboard.js' {
  declare module.exports: $Exports<'frog-utils/src/dashboards/leaderboard'>;
}
declare module 'frog-utils/src/dashboards/progress.js' {
  declare module.exports: $Exports<'frog-utils/src/dashboards/progress'>;
}
declare module 'frog-utils/src/dataStructureTools.js' {
  declare module.exports: $Exports<'frog-utils/src/dataStructureTools'>;
}
declare module 'frog-utils/src/EnhancedForm.js' {
  declare module.exports: $Exports<'frog-utils/src/EnhancedForm'>;
}
declare module 'frog-utils/src/enhancedFormUtils.js' {
  declare module.exports: $Exports<'frog-utils/src/enhancedFormUtils'>;
}
declare module 'frog-utils/src/generateReactiveFn.js' {
  declare module.exports: $Exports<'frog-utils/src/generateReactiveFn'>;
}
declare module 'frog-utils/src/generateReactiveMem.js' {
  declare module.exports: $Exports<'frog-utils/src/generateReactiveMem'>;
}
declare module 'frog-utils/src/highlightSubstring.js' {
  declare module.exports: $Exports<'frog-utils/src/highlightSubstring'>;
}
declare module 'frog-utils/src/ImageReload.js' {
  declare module.exports: $Exports<'frog-utils/src/ImageReload'>;
}
declare module 'frog-utils/src/index.js' {
  declare module.exports: $Exports<'frog-utils/src/index'>;
}
declare module 'frog-utils/src/msToString.js' {
  declare module.exports: $Exports<'frog-utils/src/msToString'>;
}
declare module 'frog-utils/src/ReactiveText.js' {
  declare module.exports: $Exports<'frog-utils/src/ReactiveText'>;
}
declare module 'frog-utils/src/renderHTML.js' {
  declare module.exports: $Exports<'frog-utils/src/renderHTML'>;
}
declare module 'frog-utils/src/resizeDataURL.js' {
  declare module.exports: $Exports<'frog-utils/src/resizeDataURL'>;
}
declare module 'frog-utils/src/socstructTools.js' {
  declare module.exports: $Exports<'frog-utils/src/socstructTools'>;
}
declare module 'frog-utils/src/strfTime.js' {
  declare module.exports: $Exports<'frog-utils/src/strfTime'>;
}
declare module 'frog-utils/src/TextInput.js' {
  declare module.exports: $Exports<'frog-utils/src/TextInput'>;
}
declare module 'frog-utils/src/TimedComponent.js' {
  declare module.exports: $Exports<'frog-utils/src/TimedComponent'>;
}
declare module 'frog-utils/src/types.js' {
  declare module.exports: $Exports<'frog-utils/src/types'>;
}
declare module 'frog-utils/src/unrollProducts.js' {
  declare module.exports: $Exports<'frog-utils/src/unrollProducts'>;
}
declare module 'frog-utils/src/URLtoFile.js' {
  declare module.exports: $Exports<'frog-utils/src/URLtoFile'>;
}
declare module 'frog-utils/src/withDragDropContext.js' {
  declare module.exports: $Exports<'frog-utils/src/withDragDropContext'>;
}
