// flow-typed signature: c54c443d1fcfb03f0e9d849770c07991
// flow-typed version: <<STUB>>/jest-cli_v^24.1.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-cli/bin/jest' {
  declare module.exports: any;
}

declare module 'jest-cli/build/cli/args' {
  declare module.exports: any;
}

declare module 'jest-cli/build/cli/index' {
  declare module.exports: any;
}

declare module 'jest-cli/build/collectHandles' {
  declare module.exports: any;
}

declare module 'jest-cli/build/constants' {
  declare module.exports: any;
}

declare module 'jest-cli/build/FailedTestsCache' {
  declare module.exports: any;
}

declare module 'jest-cli/build/generateEmptyCoverage' {
  declare module.exports: any;
}

declare module 'jest-cli/build/getChangedFilesPromise' {
  declare module.exports: any;
}

declare module 'jest-cli/build/getNoTestFound' {
  declare module.exports: any;
}

declare module 'jest-cli/build/getNoTestFoundFailed' {
  declare module.exports: any;
}

declare module 'jest-cli/build/getNoTestFoundRelatedToChangedFiles' {
  declare module.exports: any;
}

declare module 'jest-cli/build/getNoTestFoundVerbose' {
  declare module.exports: any;
}

declare module 'jest-cli/build/getNoTestsFoundMessage' {
  declare module.exports: any;
}

declare module 'jest-cli/build/jest' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/active_filters_message' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/create_context' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/handle_deprecation_warnings' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/init/errors' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/init/generate_config_file' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/init/index' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/init/modify_package_json' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/init/questions' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/is_valid_path' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/log_debug_messages' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/update_global_config' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/watch_plugins_helpers' {
  declare module.exports: any;
}

declare module 'jest-cli/build/plugins/quit' {
  declare module.exports: any;
}

declare module 'jest-cli/build/plugins/test_name_pattern' {
  declare module.exports: any;
}

declare module 'jest-cli/build/plugins/test_path_pattern' {
  declare module.exports: any;
}

declare module 'jest-cli/build/plugins/update_snapshots_interactive' {
  declare module.exports: any;
}

declare module 'jest-cli/build/plugins/update_snapshots' {
  declare module.exports: any;
}

declare module 'jest-cli/build/pluralize' {
  declare module.exports: any;
}

declare module 'jest-cli/build/preRunMessage' {
  declare module.exports: any;
}

declare module 'jest-cli/build/ReporterDispatcher' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/base_reporter' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/coverage_reporter' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/coverage_worker' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/default_reporter' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/get_result_header' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/get_snapshot_status' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/get_snapshot_summary' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/notify_reporter' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/Status' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/summary_reporter' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/utils' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/verbose_reporter' {
  declare module.exports: any;
}

declare module 'jest-cli/build/runGlobalHook' {
  declare module.exports: any;
}

declare module 'jest-cli/build/runJest' {
  declare module.exports: any;
}

declare module 'jest-cli/build/SearchSource' {
  declare module.exports: any;
}

declare module 'jest-cli/build/SnapshotInteractiveMode' {
  declare module.exports: any;
}

declare module 'jest-cli/build/TestNamePatternPrompt' {
  declare module.exports: any;
}

declare module 'jest-cli/build/TestPathPatternPrompt' {
  declare module.exports: any;
}

declare module 'jest-cli/build/testPathPatternToRegexp' {
  declare module.exports: any;
}

declare module 'jest-cli/build/testResultHelpers' {
  declare module.exports: any;
}

declare module 'jest-cli/build/TestScheduler' {
  declare module.exports: any;
}

declare module 'jest-cli/build/testSchedulerHelper' {
  declare module.exports: any;
}

declare module 'jest-cli/build/TestSequencer' {
  declare module.exports: any;
}

declare module 'jest-cli/build/TestWatcher' {
  declare module.exports: any;
}

declare module 'jest-cli/build/types' {
  declare module.exports: any;
}

declare module 'jest-cli/build/version' {
  declare module.exports: any;
}

declare module 'jest-cli/build/watch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-cli/bin/jest.js' {
  declare module.exports: $Exports<'jest-cli/bin/jest'>;
}
declare module 'jest-cli/build/cli/args.js' {
  declare module.exports: $Exports<'jest-cli/build/cli/args'>;
}
declare module 'jest-cli/build/cli/index.js' {
  declare module.exports: $Exports<'jest-cli/build/cli/index'>;
}
declare module 'jest-cli/build/collectHandles.js' {
  declare module.exports: $Exports<'jest-cli/build/collectHandles'>;
}
declare module 'jest-cli/build/constants.js' {
  declare module.exports: $Exports<'jest-cli/build/constants'>;
}
declare module 'jest-cli/build/FailedTestsCache.js' {
  declare module.exports: $Exports<'jest-cli/build/FailedTestsCache'>;
}
declare module 'jest-cli/build/generateEmptyCoverage.js' {
  declare module.exports: $Exports<'jest-cli/build/generateEmptyCoverage'>;
}
declare module 'jest-cli/build/getChangedFilesPromise.js' {
  declare module.exports: $Exports<'jest-cli/build/getChangedFilesPromise'>;
}
declare module 'jest-cli/build/getNoTestFound.js' {
  declare module.exports: $Exports<'jest-cli/build/getNoTestFound'>;
}
declare module 'jest-cli/build/getNoTestFoundFailed.js' {
  declare module.exports: $Exports<'jest-cli/build/getNoTestFoundFailed'>;
}
declare module 'jest-cli/build/getNoTestFoundRelatedToChangedFiles.js' {
  declare module.exports: $Exports<'jest-cli/build/getNoTestFoundRelatedToChangedFiles'>;
}
declare module 'jest-cli/build/getNoTestFoundVerbose.js' {
  declare module.exports: $Exports<'jest-cli/build/getNoTestFoundVerbose'>;
}
declare module 'jest-cli/build/getNoTestsFoundMessage.js' {
  declare module.exports: $Exports<'jest-cli/build/getNoTestsFoundMessage'>;
}
declare module 'jest-cli/build/jest.js' {
  declare module.exports: $Exports<'jest-cli/build/jest'>;
}
declare module 'jest-cli/build/lib/active_filters_message.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/active_filters_message'>;
}
declare module 'jest-cli/build/lib/create_context.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/create_context'>;
}
declare module 'jest-cli/build/lib/handle_deprecation_warnings.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/handle_deprecation_warnings'>;
}
declare module 'jest-cli/build/lib/init/errors.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/init/errors'>;
}
declare module 'jest-cli/build/lib/init/generate_config_file.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/init/generate_config_file'>;
}
declare module 'jest-cli/build/lib/init/index.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/init/index'>;
}
declare module 'jest-cli/build/lib/init/modify_package_json.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/init/modify_package_json'>;
}
declare module 'jest-cli/build/lib/init/questions.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/init/questions'>;
}
declare module 'jest-cli/build/lib/is_valid_path.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/is_valid_path'>;
}
declare module 'jest-cli/build/lib/log_debug_messages.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/log_debug_messages'>;
}
declare module 'jest-cli/build/lib/update_global_config.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/update_global_config'>;
}
declare module 'jest-cli/build/lib/watch_plugins_helpers.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/watch_plugins_helpers'>;
}
declare module 'jest-cli/build/plugins/quit.js' {
  declare module.exports: $Exports<'jest-cli/build/plugins/quit'>;
}
declare module 'jest-cli/build/plugins/test_name_pattern.js' {
  declare module.exports: $Exports<'jest-cli/build/plugins/test_name_pattern'>;
}
declare module 'jest-cli/build/plugins/test_path_pattern.js' {
  declare module.exports: $Exports<'jest-cli/build/plugins/test_path_pattern'>;
}
declare module 'jest-cli/build/plugins/update_snapshots_interactive.js' {
  declare module.exports: $Exports<'jest-cli/build/plugins/update_snapshots_interactive'>;
}
declare module 'jest-cli/build/plugins/update_snapshots.js' {
  declare module.exports: $Exports<'jest-cli/build/plugins/update_snapshots'>;
}
declare module 'jest-cli/build/pluralize.js' {
  declare module.exports: $Exports<'jest-cli/build/pluralize'>;
}
declare module 'jest-cli/build/preRunMessage.js' {
  declare module.exports: $Exports<'jest-cli/build/preRunMessage'>;
}
declare module 'jest-cli/build/ReporterDispatcher.js' {
  declare module.exports: $Exports<'jest-cli/build/ReporterDispatcher'>;
}
declare module 'jest-cli/build/reporters/base_reporter.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/base_reporter'>;
}
declare module 'jest-cli/build/reporters/coverage_reporter.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/coverage_reporter'>;
}
declare module 'jest-cli/build/reporters/coverage_worker.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/coverage_worker'>;
}
declare module 'jest-cli/build/reporters/default_reporter.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/default_reporter'>;
}
declare module 'jest-cli/build/reporters/get_result_header.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/get_result_header'>;
}
declare module 'jest-cli/build/reporters/get_snapshot_status.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/get_snapshot_status'>;
}
declare module 'jest-cli/build/reporters/get_snapshot_summary.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/get_snapshot_summary'>;
}
declare module 'jest-cli/build/reporters/notify_reporter.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/notify_reporter'>;
}
declare module 'jest-cli/build/reporters/Status.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/Status'>;
}
declare module 'jest-cli/build/reporters/summary_reporter.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/summary_reporter'>;
}
declare module 'jest-cli/build/reporters/utils.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/utils'>;
}
declare module 'jest-cli/build/reporters/verbose_reporter.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/verbose_reporter'>;
}
declare module 'jest-cli/build/runGlobalHook.js' {
  declare module.exports: $Exports<'jest-cli/build/runGlobalHook'>;
}
declare module 'jest-cli/build/runJest.js' {
  declare module.exports: $Exports<'jest-cli/build/runJest'>;
}
declare module 'jest-cli/build/SearchSource.js' {
  declare module.exports: $Exports<'jest-cli/build/SearchSource'>;
}
declare module 'jest-cli/build/SnapshotInteractiveMode.js' {
  declare module.exports: $Exports<'jest-cli/build/SnapshotInteractiveMode'>;
}
declare module 'jest-cli/build/TestNamePatternPrompt.js' {
  declare module.exports: $Exports<'jest-cli/build/TestNamePatternPrompt'>;
}
declare module 'jest-cli/build/TestPathPatternPrompt.js' {
  declare module.exports: $Exports<'jest-cli/build/TestPathPatternPrompt'>;
}
declare module 'jest-cli/build/testPathPatternToRegexp.js' {
  declare module.exports: $Exports<'jest-cli/build/testPathPatternToRegexp'>;
}
declare module 'jest-cli/build/testResultHelpers.js' {
  declare module.exports: $Exports<'jest-cli/build/testResultHelpers'>;
}
declare module 'jest-cli/build/TestScheduler.js' {
  declare module.exports: $Exports<'jest-cli/build/TestScheduler'>;
}
declare module 'jest-cli/build/testSchedulerHelper.js' {
  declare module.exports: $Exports<'jest-cli/build/testSchedulerHelper'>;
}
declare module 'jest-cli/build/TestSequencer.js' {
  declare module.exports: $Exports<'jest-cli/build/TestSequencer'>;
}
declare module 'jest-cli/build/TestWatcher.js' {
  declare module.exports: $Exports<'jest-cli/build/TestWatcher'>;
}
declare module 'jest-cli/build/types.js' {
  declare module.exports: $Exports<'jest-cli/build/types'>;
}
declare module 'jest-cli/build/version.js' {
  declare module.exports: $Exports<'jest-cli/build/version'>;
}
declare module 'jest-cli/build/watch.js' {
  declare module.exports: $Exports<'jest-cli/build/watch'>;
}
