// flow-typed signature: 50a4f858d000ca6d3fc96543a7d866a0
// flow-typed version: <<STUB>>/jest-config_v^24.1.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-config/build/constants' {
  declare module.exports: any;
}

declare module 'jest-config/build/Defaults' {
  declare module.exports: any;
}

declare module 'jest-config/build/Deprecated' {
  declare module.exports: any;
}

declare module 'jest-config/build/Descriptions' {
  declare module.exports: any;
}

declare module 'jest-config/build/getCacheDirectory' {
  declare module.exports: any;
}

declare module 'jest-config/build/getMaxWorkers' {
  declare module.exports: any;
}

declare module 'jest-config/build/index' {
  declare module.exports: any;
}

declare module 'jest-config/build/normalize' {
  declare module.exports: any;
}

declare module 'jest-config/build/readConfigFileAndSetRootDir' {
  declare module.exports: any;
}

declare module 'jest-config/build/ReporterValidationErrors' {
  declare module.exports: any;
}

declare module 'jest-config/build/resolveConfigPath' {
  declare module.exports: any;
}

declare module 'jest-config/build/setFromArgv' {
  declare module.exports: any;
}

declare module 'jest-config/build/utils' {
  declare module.exports: any;
}

declare module 'jest-config/build/validatePattern' {
  declare module.exports: any;
}

declare module 'jest-config/build/ValidConfig' {
  declare module.exports: any;
}

declare module 'jest-config/build/vendor/jsonlint' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-config/build/constants.js' {
  declare module.exports: $Exports<'jest-config/build/constants'>;
}
declare module 'jest-config/build/Defaults.js' {
  declare module.exports: $Exports<'jest-config/build/Defaults'>;
}
declare module 'jest-config/build/Deprecated.js' {
  declare module.exports: $Exports<'jest-config/build/Deprecated'>;
}
declare module 'jest-config/build/Descriptions.js' {
  declare module.exports: $Exports<'jest-config/build/Descriptions'>;
}
declare module 'jest-config/build/getCacheDirectory.js' {
  declare module.exports: $Exports<'jest-config/build/getCacheDirectory'>;
}
declare module 'jest-config/build/getMaxWorkers.js' {
  declare module.exports: $Exports<'jest-config/build/getMaxWorkers'>;
}
declare module 'jest-config/build/index.js' {
  declare module.exports: $Exports<'jest-config/build/index'>;
}
declare module 'jest-config/build/normalize.js' {
  declare module.exports: $Exports<'jest-config/build/normalize'>;
}
declare module 'jest-config/build/readConfigFileAndSetRootDir.js' {
  declare module.exports: $Exports<'jest-config/build/readConfigFileAndSetRootDir'>;
}
declare module 'jest-config/build/ReporterValidationErrors.js' {
  declare module.exports: $Exports<'jest-config/build/ReporterValidationErrors'>;
}
declare module 'jest-config/build/resolveConfigPath.js' {
  declare module.exports: $Exports<'jest-config/build/resolveConfigPath'>;
}
declare module 'jest-config/build/setFromArgv.js' {
  declare module.exports: $Exports<'jest-config/build/setFromArgv'>;
}
declare module 'jest-config/build/utils.js' {
  declare module.exports: $Exports<'jest-config/build/utils'>;
}
declare module 'jest-config/build/validatePattern.js' {
  declare module.exports: $Exports<'jest-config/build/validatePattern'>;
}
declare module 'jest-config/build/ValidConfig.js' {
  declare module.exports: $Exports<'jest-config/build/ValidConfig'>;
}
declare module 'jest-config/build/vendor/jsonlint.js' {
  declare module.exports: $Exports<'jest-config/build/vendor/jsonlint'>;
}
