// flow-typed signature: 94eadce3422152b785da86a841f311c1
// flow-typed version: <<STUB>>/jest-runtime_v^24.1.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-runtime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-runtime' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-runtime/bin/jest-runtime' {
  declare module.exports: any;
}

declare module 'jest-runtime/build/cli/args' {
  declare module.exports: any;
}

declare module 'jest-runtime/build/cli/index' {
  declare module.exports: any;
}

declare module 'jest-runtime/build/helpers' {
  declare module.exports: any;
}

declare module 'jest-runtime/build/index' {
  declare module.exports: any;
}

declare module 'jest-runtime/build/ScriptTransformer' {
  declare module.exports: any;
}

declare module 'jest-runtime/build/shouldInstrument' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-runtime/bin/jest-runtime.js' {
  declare module.exports: $Exports<'jest-runtime/bin/jest-runtime'>;
}
declare module 'jest-runtime/build/cli/args.js' {
  declare module.exports: $Exports<'jest-runtime/build/cli/args'>;
}
declare module 'jest-runtime/build/cli/index.js' {
  declare module.exports: $Exports<'jest-runtime/build/cli/index'>;
}
declare module 'jest-runtime/build/helpers.js' {
  declare module.exports: $Exports<'jest-runtime/build/helpers'>;
}
declare module 'jest-runtime/build/index.js' {
  declare module.exports: $Exports<'jest-runtime/build/index'>;
}
declare module 'jest-runtime/build/ScriptTransformer.js' {
  declare module.exports: $Exports<'jest-runtime/build/ScriptTransformer'>;
}
declare module 'jest-runtime/build/shouldInstrument.js' {
  declare module.exports: $Exports<'jest-runtime/build/shouldInstrument'>;
}
