// flow-typed signature: f87842cc475c50fdc37d8be92cb99927
// flow-typed version: <<STUB>>/jest-runner_v^24.1.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-runner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-runner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-runner/build/index' {
  declare module.exports: any;
}

declare module 'jest-runner/build/runTest' {
  declare module.exports: any;
}

declare module 'jest-runner/build/testWorker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-runner/build/index.js' {
  declare module.exports: $Exports<'jest-runner/build/index'>;
}
declare module 'jest-runner/build/runTest.js' {
  declare module.exports: $Exports<'jest-runner/build/runTest'>;
}
declare module 'jest-runner/build/testWorker.js' {
  declare module.exports: $Exports<'jest-runner/build/testWorker'>;
}
