// flow-typed signature: 790672e751d37401c4bc4ba8e8e487ca
// flow-typed version: <<STUB>>/json-stable-stringify_v^1.0.1/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json-stable-stringify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'json-stable-stringify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'json-stable-stringify/example/key_cmp' {
  declare module.exports: any;
}

declare module 'json-stable-stringify/example/nested' {
  declare module.exports: any;
}

declare module 'json-stable-stringify/example/str' {
  declare module.exports: any;
}

declare module 'json-stable-stringify/example/value_cmp' {
  declare module.exports: any;
}

declare module 'json-stable-stringify/test/cmp' {
  declare module.exports: any;
}

declare module 'json-stable-stringify/test/nested' {
  declare module.exports: any;
}

declare module 'json-stable-stringify/test/replacer' {
  declare module.exports: any;
}

declare module 'json-stable-stringify/test/space' {
  declare module.exports: any;
}

declare module 'json-stable-stringify/test/str' {
  declare module.exports: any;
}

declare module 'json-stable-stringify/test/to-json' {
  declare module.exports: any;
}

// Filename aliases
declare module 'json-stable-stringify/example/key_cmp.js' {
  declare module.exports: $Exports<'json-stable-stringify/example/key_cmp'>;
}
declare module 'json-stable-stringify/example/nested.js' {
  declare module.exports: $Exports<'json-stable-stringify/example/nested'>;
}
declare module 'json-stable-stringify/example/str.js' {
  declare module.exports: $Exports<'json-stable-stringify/example/str'>;
}
declare module 'json-stable-stringify/example/value_cmp.js' {
  declare module.exports: $Exports<'json-stable-stringify/example/value_cmp'>;
}
declare module 'json-stable-stringify/index' {
  declare module.exports: $Exports<'json-stable-stringify'>;
}
declare module 'json-stable-stringify/index.js' {
  declare module.exports: $Exports<'json-stable-stringify'>;
}
declare module 'json-stable-stringify/test/cmp.js' {
  declare module.exports: $Exports<'json-stable-stringify/test/cmp'>;
}
declare module 'json-stable-stringify/test/nested.js' {
  declare module.exports: $Exports<'json-stable-stringify/test/nested'>;
}
declare module 'json-stable-stringify/test/replacer.js' {
  declare module.exports: $Exports<'json-stable-stringify/test/replacer'>;
}
declare module 'json-stable-stringify/test/space.js' {
  declare module.exports: $Exports<'json-stable-stringify/test/space'>;
}
declare module 'json-stable-stringify/test/str.js' {
  declare module.exports: $Exports<'json-stable-stringify/test/str'>;
}
declare module 'json-stable-stringify/test/to-json.js' {
  declare module.exports: $Exports<'json-stable-stringify/test/to-json'>;
}
