// flow-typed signature: aeafed3045b40d0d4c2764a71d89e316
// flow-typed version: <<STUB>>/json-schema-defaults_v^0.4.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json-schema-defaults'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'json-schema-defaults' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'json-schema-defaults/bin/defaults' {
  declare module.exports: any;
}

declare module 'json-schema-defaults/Gruntfile' {
  declare module.exports: any;
}

declare module 'json-schema-defaults/karma.conf' {
  declare module.exports: any;
}

declare module 'json-schema-defaults/lib/defaults' {
  declare module.exports: any;
}

// Filename aliases
declare module 'json-schema-defaults/bin/defaults.js' {
  declare module.exports: $Exports<'json-schema-defaults/bin/defaults'>;
}
declare module 'json-schema-defaults/Gruntfile.js' {
  declare module.exports: $Exports<'json-schema-defaults/Gruntfile'>;
}
declare module 'json-schema-defaults/index' {
  declare module.exports: $Exports<'json-schema-defaults'>;
}
declare module 'json-schema-defaults/index.js' {
  declare module.exports: $Exports<'json-schema-defaults'>;
}
declare module 'json-schema-defaults/karma.conf.js' {
  declare module.exports: $Exports<'json-schema-defaults/karma.conf'>;
}
declare module 'json-schema-defaults/lib/defaults.js' {
  declare module.exports: $Exports<'json-schema-defaults/lib/defaults'>;
}
