// flow-typed signature: 578d1fada051180e98cd3fba615f2d30
// flow-typed version: <<STUB>>/meteor-node-stubs_v^0.4.1/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'meteor-node-stubs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'meteor-node-stubs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'meteor-node-stubs/deps/_stream_duplex' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/_stream_passthrough' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/_stream_readable' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/_stream_transform' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/_stream_writable' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/assert' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/buffer' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/child_process' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/cluster' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/console' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/constants' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/crypto' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/dgram' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/dns' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/domain' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/events' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/fs' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/http' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/https' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/module' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/net' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/os' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/path' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/process' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/punycode' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/querystring' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/readline' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/repl' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/stream' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/string_decoder' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/sys' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/timers' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/tls' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/tty' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/url' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/util' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/vm' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/deps/zlib' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/scripts/build-deps' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/wrappers/crypto' {
  declare module.exports: any;
}

declare module 'meteor-node-stubs/wrappers/module' {
  declare module.exports: any;
}

// Filename aliases
declare module 'meteor-node-stubs/deps/_stream_duplex.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/_stream_duplex'>;
}
declare module 'meteor-node-stubs/deps/_stream_passthrough.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/_stream_passthrough'>;
}
declare module 'meteor-node-stubs/deps/_stream_readable.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/_stream_readable'>;
}
declare module 'meteor-node-stubs/deps/_stream_transform.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/_stream_transform'>;
}
declare module 'meteor-node-stubs/deps/_stream_writable.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/_stream_writable'>;
}
declare module 'meteor-node-stubs/deps/assert.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/assert'>;
}
declare module 'meteor-node-stubs/deps/buffer.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/buffer'>;
}
declare module 'meteor-node-stubs/deps/child_process.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/child_process'>;
}
declare module 'meteor-node-stubs/deps/cluster.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/cluster'>;
}
declare module 'meteor-node-stubs/deps/console.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/console'>;
}
declare module 'meteor-node-stubs/deps/constants.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/constants'>;
}
declare module 'meteor-node-stubs/deps/crypto.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/crypto'>;
}
declare module 'meteor-node-stubs/deps/dgram.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/dgram'>;
}
declare module 'meteor-node-stubs/deps/dns.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/dns'>;
}
declare module 'meteor-node-stubs/deps/domain.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/domain'>;
}
declare module 'meteor-node-stubs/deps/events.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/events'>;
}
declare module 'meteor-node-stubs/deps/fs.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/fs'>;
}
declare module 'meteor-node-stubs/deps/http.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/http'>;
}
declare module 'meteor-node-stubs/deps/https.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/https'>;
}
declare module 'meteor-node-stubs/deps/module.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/module'>;
}
declare module 'meteor-node-stubs/deps/net.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/net'>;
}
declare module 'meteor-node-stubs/deps/os.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/os'>;
}
declare module 'meteor-node-stubs/deps/path.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/path'>;
}
declare module 'meteor-node-stubs/deps/process.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/process'>;
}
declare module 'meteor-node-stubs/deps/punycode.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/punycode'>;
}
declare module 'meteor-node-stubs/deps/querystring.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/querystring'>;
}
declare module 'meteor-node-stubs/deps/readline.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/readline'>;
}
declare module 'meteor-node-stubs/deps/repl.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/repl'>;
}
declare module 'meteor-node-stubs/deps/stream.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/stream'>;
}
declare module 'meteor-node-stubs/deps/string_decoder.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/string_decoder'>;
}
declare module 'meteor-node-stubs/deps/sys.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/sys'>;
}
declare module 'meteor-node-stubs/deps/timers.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/timers'>;
}
declare module 'meteor-node-stubs/deps/tls.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/tls'>;
}
declare module 'meteor-node-stubs/deps/tty.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/tty'>;
}
declare module 'meteor-node-stubs/deps/url.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/url'>;
}
declare module 'meteor-node-stubs/deps/util.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/util'>;
}
declare module 'meteor-node-stubs/deps/vm.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/vm'>;
}
declare module 'meteor-node-stubs/deps/zlib.js' {
  declare module.exports: $Exports<'meteor-node-stubs/deps/zlib'>;
}
declare module 'meteor-node-stubs/index' {
  declare module.exports: $Exports<'meteor-node-stubs'>;
}
declare module 'meteor-node-stubs/index.js' {
  declare module.exports: $Exports<'meteor-node-stubs'>;
}
declare module 'meteor-node-stubs/scripts/build-deps.js' {
  declare module.exports: $Exports<'meteor-node-stubs/scripts/build-deps'>;
}
declare module 'meteor-node-stubs/wrappers/crypto.js' {
  declare module.exports: $Exports<'meteor-node-stubs/wrappers/crypto'>;
}
declare module 'meteor-node-stubs/wrappers/module.js' {
  declare module.exports: $Exports<'meteor-node-stubs/wrappers/module'>;
}
