// flow-typed signature: eceacb2e4095e0b3aa5df544349996d1
// flow-typed version: <<STUB>>/minio_v^3.2.3/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'minio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'minio' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'minio/dist/main/bucket-policy' {
  declare module.exports: any;
}

declare module 'minio/dist/main/errors' {
  declare module.exports: any;
}

declare module 'minio/dist/main/helpers' {
  declare module.exports: any;
}

declare module 'minio/dist/main/minio' {
  declare module.exports: any;
}

declare module 'minio/dist/main/notification' {
  declare module.exports: any;
}

declare module 'minio/dist/main/object-uploader' {
  declare module.exports: any;
}

declare module 'minio/dist/main/s3-endpoints' {
  declare module.exports: any;
}

declare module 'minio/dist/main/signing' {
  declare module.exports: any;
}

declare module 'minio/dist/main/transformers' {
  declare module.exports: any;
}

declare module 'minio/dist/main/xml-parsers' {
  declare module.exports: any;
}

declare module 'minio/examples/bucket-exists' {
  declare module.exports: any;
}

declare module 'minio/examples/copy-object' {
  declare module.exports: any;
}

declare module 'minio/examples/fget-object' {
  declare module.exports: any;
}

declare module 'minio/examples/fput-object' {
  declare module.exports: any;
}

declare module 'minio/examples/get-bucket-notification' {
  declare module.exports: any;
}

declare module 'minio/examples/get-bucket-policy' {
  declare module.exports: any;
}

declare module 'minio/examples/get-object' {
  declare module.exports: any;
}

declare module 'minio/examples/get-partialobject' {
  declare module.exports: any;
}

declare module 'minio/examples/list-buckets' {
  declare module.exports: any;
}

declare module 'minio/examples/list-incomplete-uploads' {
  declare module.exports: any;
}

declare module 'minio/examples/list-objects-v2' {
  declare module.exports: any;
}

declare module 'minio/examples/list-objects' {
  declare module.exports: any;
}

declare module 'minio/examples/make-bucket' {
  declare module.exports: any;
}

declare module 'minio/examples/minio/listen-bucket-notification' {
  declare module.exports: any;
}

declare module 'minio/examples/presigned-getobject' {
  declare module.exports: any;
}

declare module 'minio/examples/presigned-postpolicy' {
  declare module.exports: any;
}

declare module 'minio/examples/presigned-putobject' {
  declare module.exports: any;
}

declare module 'minio/examples/put-object' {
  declare module.exports: any;
}

declare module 'minio/examples/remove-all-bucket-notification' {
  declare module.exports: any;
}

declare module 'minio/examples/remove-bucket' {
  declare module.exports: any;
}

declare module 'minio/examples/remove-incomplete-upload' {
  declare module.exports: any;
}

declare module 'minio/examples/remove-object' {
  declare module.exports: any;
}

declare module 'minio/examples/set-bucket-notification' {
  declare module.exports: any;
}

declare module 'minio/examples/set-bucket-policy' {
  declare module.exports: any;
}

declare module 'minio/examples/stat-object' {
  declare module.exports: any;
}

declare module 'minio/gulpfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'minio/dist/main/bucket-policy.js' {
  declare module.exports: $Exports<'minio/dist/main/bucket-policy'>;
}
declare module 'minio/dist/main/errors.js' {
  declare module.exports: $Exports<'minio/dist/main/errors'>;
}
declare module 'minio/dist/main/helpers.js' {
  declare module.exports: $Exports<'minio/dist/main/helpers'>;
}
declare module 'minio/dist/main/minio.js' {
  declare module.exports: $Exports<'minio/dist/main/minio'>;
}
declare module 'minio/dist/main/notification.js' {
  declare module.exports: $Exports<'minio/dist/main/notification'>;
}
declare module 'minio/dist/main/object-uploader.js' {
  declare module.exports: $Exports<'minio/dist/main/object-uploader'>;
}
declare module 'minio/dist/main/s3-endpoints.js' {
  declare module.exports: $Exports<'minio/dist/main/s3-endpoints'>;
}
declare module 'minio/dist/main/signing.js' {
  declare module.exports: $Exports<'minio/dist/main/signing'>;
}
declare module 'minio/dist/main/transformers.js' {
  declare module.exports: $Exports<'minio/dist/main/transformers'>;
}
declare module 'minio/dist/main/xml-parsers.js' {
  declare module.exports: $Exports<'minio/dist/main/xml-parsers'>;
}
declare module 'minio/examples/bucket-exists.js' {
  declare module.exports: $Exports<'minio/examples/bucket-exists'>;
}
declare module 'minio/examples/copy-object.js' {
  declare module.exports: $Exports<'minio/examples/copy-object'>;
}
declare module 'minio/examples/fget-object.js' {
  declare module.exports: $Exports<'minio/examples/fget-object'>;
}
declare module 'minio/examples/fput-object.js' {
  declare module.exports: $Exports<'minio/examples/fput-object'>;
}
declare module 'minio/examples/get-bucket-notification.js' {
  declare module.exports: $Exports<'minio/examples/get-bucket-notification'>;
}
declare module 'minio/examples/get-bucket-policy.js' {
  declare module.exports: $Exports<'minio/examples/get-bucket-policy'>;
}
declare module 'minio/examples/get-object.js' {
  declare module.exports: $Exports<'minio/examples/get-object'>;
}
declare module 'minio/examples/get-partialobject.js' {
  declare module.exports: $Exports<'minio/examples/get-partialobject'>;
}
declare module 'minio/examples/list-buckets.js' {
  declare module.exports: $Exports<'minio/examples/list-buckets'>;
}
declare module 'minio/examples/list-incomplete-uploads.js' {
  declare module.exports: $Exports<'minio/examples/list-incomplete-uploads'>;
}
declare module 'minio/examples/list-objects-v2.js' {
  declare module.exports: $Exports<'minio/examples/list-objects-v2'>;
}
declare module 'minio/examples/list-objects.js' {
  declare module.exports: $Exports<'minio/examples/list-objects'>;
}
declare module 'minio/examples/make-bucket.js' {
  declare module.exports: $Exports<'minio/examples/make-bucket'>;
}
declare module 'minio/examples/minio/listen-bucket-notification.js' {
  declare module.exports: $Exports<'minio/examples/minio/listen-bucket-notification'>;
}
declare module 'minio/examples/presigned-getobject.js' {
  declare module.exports: $Exports<'minio/examples/presigned-getobject'>;
}
declare module 'minio/examples/presigned-postpolicy.js' {
  declare module.exports: $Exports<'minio/examples/presigned-postpolicy'>;
}
declare module 'minio/examples/presigned-putobject.js' {
  declare module.exports: $Exports<'minio/examples/presigned-putobject'>;
}
declare module 'minio/examples/put-object.js' {
  declare module.exports: $Exports<'minio/examples/put-object'>;
}
declare module 'minio/examples/remove-all-bucket-notification.js' {
  declare module.exports: $Exports<'minio/examples/remove-all-bucket-notification'>;
}
declare module 'minio/examples/remove-bucket.js' {
  declare module.exports: $Exports<'minio/examples/remove-bucket'>;
}
declare module 'minio/examples/remove-incomplete-upload.js' {
  declare module.exports: $Exports<'minio/examples/remove-incomplete-upload'>;
}
declare module 'minio/examples/remove-object.js' {
  declare module.exports: $Exports<'minio/examples/remove-object'>;
}
declare module 'minio/examples/set-bucket-notification.js' {
  declare module.exports: $Exports<'minio/examples/set-bucket-notification'>;
}
declare module 'minio/examples/set-bucket-policy.js' {
  declare module.exports: $Exports<'minio/examples/set-bucket-policy'>;
}
declare module 'minio/examples/stat-object.js' {
  declare module.exports: $Exports<'minio/examples/stat-object'>;
}
declare module 'minio/gulpfile.js' {
  declare module.exports: $Exports<'minio/gulpfile'>;
}
