// flow-typed signature: e32dd83957716a7a2877dc5d10e7a526
// flow-typed version: <<STUB>>/mobx-react-devtools_v^5.0.1/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mobx-react-devtools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mobx-react-devtools' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mobx-react-devtools/publish' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mobx-react-devtools/index' {
  declare module.exports: $Exports<'mobx-react-devtools'>;
}
declare module 'mobx-react-devtools/index.js' {
  declare module.exports: $Exports<'mobx-react-devtools'>;
}
declare module 'mobx-react-devtools/publish.js' {
  declare module.exports: $Exports<'mobx-react-devtools/publish'>;
}
