// flow-typed signature: 350511d95ea55d1e613be0300b2b9cfb
// flow-typed version: <<STUB>>/op-argue-constraint_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'op-argue-constraint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'op-argue-constraint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'op-argue-constraint/src/__tests__/index' {
  declare module.exports: any;
}

declare module 'op-argue-constraint/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'op-argue-constraint/src/__tests__/index.js' {
  declare module.exports: $Exports<'op-argue-constraint/src/__tests__/index'>;
}
declare module 'op-argue-constraint/src/index.js' {
  declare module.exports: $Exports<'op-argue-constraint/src/index'>;
}
