// flow-typed signature: 9564d1aa610472ad45df691f6a4d146d
// flow-typed version: <<STUB>>/op-check-concepts_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'op-check-concepts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'op-check-concepts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'op-check-concepts/src/__tests__/index' {
  declare module.exports: any;
}

declare module 'op-check-concepts/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'op-check-concepts/src/__tests__/index.js' {
  declare module.exports: $Exports<'op-check-concepts/src/__tests__/index'>;
}
declare module 'op-check-concepts/src/index.js' {
  declare module.exports: $Exports<'op-check-concepts/src/index'>;
}
