// flow-typed signature: 4f8be496818216bc17121ff8269940c1
// flow-typed version: <<STUB>>/op-control-group_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'op-control-group'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'op-control-group' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'op-control-group/src/config' {
  declare module.exports: any;
}

declare module 'op-control-group/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'op-control-group/src/config.js' {
  declare module.exports: $Exports<'op-control-group/src/config'>;
}
declare module 'op-control-group/src/index.js' {
  declare module.exports: $Exports<'op-control-group/src/index'>;
}
