// flow-typed signature: 3faf06b47239aa127bc1cab833ef80e5
// flow-typed version: <<STUB>>/op-cs211-ranking_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'op-cs211-ranking'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'op-cs211-ranking' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'op-cs211-ranking/src/__fixtures__/object' {
  declare module.exports: any;
}

declare module 'op-cs211-ranking/src/__fixtures__/object2' {
  declare module.exports: any;
}

declare module 'op-cs211-ranking/src/__tests__/index' {
  declare module.exports: any;
}

declare module 'op-cs211-ranking/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'op-cs211-ranking/src/__fixtures__/object.js' {
  declare module.exports: $Exports<'op-cs211-ranking/src/__fixtures__/object'>;
}
declare module 'op-cs211-ranking/src/__fixtures__/object2.js' {
  declare module.exports: $Exports<'op-cs211-ranking/src/__fixtures__/object2'>;
}
declare module 'op-cs211-ranking/src/__tests__/index.js' {
  declare module.exports: $Exports<'op-cs211-ranking/src/__tests__/index'>;
}
declare module 'op-cs211-ranking/src/index.js' {
  declare module.exports: $Exports<'op-cs211-ranking/src/index'>;
}
