// flow-typed signature: ec8641b2f124cafdcfc2d76abf5bd812
// flow-typed version: <<STUB>>/op-distribute-category_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'op-distribute-category'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'op-distribute-category' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'op-distribute-category/src/__tests__/index' {
  declare module.exports: any;
}

declare module 'op-distribute-category/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'op-distribute-category/src/__tests__/index.js' {
  declare module.exports: $Exports<'op-distribute-category/src/__tests__/index'>;
}
declare module 'op-distribute-category/src/index.js' {
  declare module.exports: $Exports<'op-distribute-category/src/index'>;
}
