// flow-typed signature: 5cbe3c800bb167c37687c60779f6d7f3
// flow-typed version: <<STUB>>/op-distribute_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'op-distribute'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'op-distribute' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'op-distribute/src/__tests__/index' {
  declare module.exports: any;
}

declare module 'op-distribute/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'op-distribute/src/__tests__/index.js' {
  declare module.exports: $Exports<'op-distribute/src/__tests__/index'>;
}
declare module 'op-distribute/src/index.js' {
  declare module.exports: $Exports<'op-distribute/src/index'>;
}
