// flow-typed signature: 2da4cddce7a19c9f9da8632bfd8cdcb8
// flow-typed version: <<STUB>>/op-filter_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'op-filter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'op-filter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'op-filter/src/__tests__/index' {
  declare module.exports: any;
}

declare module 'op-filter/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'op-filter/src/__tests__/index.js' {
  declare module.exports: $Exports<'op-filter/src/__tests__/index'>;
}
declare module 'op-filter/src/index.js' {
  declare module.exports: $Exports<'op-filter/src/index'>;
}
