// flow-typed signature: 1833d2b5c0bd9e6b9e8a55dd55de53b5
// flow-typed version: <<STUB>>/op-group-identical_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'op-group-identical'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'op-group-identical' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'op-group-identical/src/__tests__/index' {
  declare module.exports: any;
}

declare module 'op-group-identical/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'op-group-identical/src/__tests__/index.js' {
  declare module.exports: $Exports<'op-group-identical/src/__tests__/index'>;
}
declare module 'op-group-identical/src/index.js' {
  declare module.exports: $Exports<'op-group-identical/src/index'>;
}
