// flow-typed signature: 16a5aecd1060a478cc37eee3bf4c4718
// flow-typed version: <<STUB>>/op-hypothesis_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'op-hypothesis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'op-hypothesis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'op-hypothesis/__mocks__/isomorphic-fetch' {
  declare module.exports: any;
}

declare module 'op-hypothesis/src/__testsdisabled__/index' {
  declare module.exports: any;
}

declare module 'op-hypothesis/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'op-hypothesis/__mocks__/isomorphic-fetch.js' {
  declare module.exports: $Exports<'op-hypothesis/__mocks__/isomorphic-fetch'>;
}
declare module 'op-hypothesis/src/__testsdisabled__/index.js' {
  declare module.exports: $Exports<'op-hypothesis/src/__testsdisabled__/index'>;
}
declare module 'op-hypothesis/src/index.js' {
  declare module.exports: $Exports<'op-hypothesis/src/index'>;
}
