// flow-typed signature: 7a40e2824fc73c4884916ade51392db3
// flow-typed version: <<STUB>>/op-jigsaw_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'op-jigsaw'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'op-jigsaw' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'op-jigsaw/src/__tests__/index' {
  declare module.exports: any;
}

declare module 'op-jigsaw/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'op-jigsaw/src/__tests__/index.js' {
  declare module.exports: $Exports<'op-jigsaw/src/__tests__/index'>;
}
declare module 'op-jigsaw/src/index.js' {
  declare module.exports: $Exports<'op-jigsaw/src/index'>;
}
