// flow-typed signature: 138059572a6d69345099eadf122bc4b2
// flow-typed version: <<STUB>>/op-prox_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'op-prox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'op-prox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'op-prox/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'op-prox/src/index.js' {
  declare module.exports: $Exports<'op-prox/src/index'>;
}
