// flow-typed signature: 9c4d316e669097424fb3b4a73fc59001
// flow-typed version: <<STUB>>/ot-json0_v^1.1.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ot-json0'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ot-json0' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ot-json0/lib/bootstrapTransform' {
  declare module.exports: any;
}

declare module 'ot-json0/lib/index' {
  declare module.exports: any;
}

declare module 'ot-json0/lib/json0' {
  declare module.exports: any;
}

declare module 'ot-json0/lib/text0' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ot-json0/lib/bootstrapTransform.js' {
  declare module.exports: $Exports<'ot-json0/lib/bootstrapTransform'>;
}
declare module 'ot-json0/lib/index.js' {
  declare module.exports: $Exports<'ot-json0/lib/index'>;
}
declare module 'ot-json0/lib/json0.js' {
  declare module.exports: $Exports<'ot-json0/lib/json0'>;
}
declare module 'ot-json0/lib/text0.js' {
  declare module.exports: $Exports<'ot-json0/lib/text0'>;
}
