// flow-typed signature: af1c39a6bc3b44d8fb3582d7e2231e82
// flow-typed version: <<STUB>>/query-parse_v^2.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'query-parse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'query-parse' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'query-parse/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'query-parse/index' {
  declare module.exports: $Exports<'query-parse'>;
}
declare module 'query-parse/index.js' {
  declare module.exports: $Exports<'query-parse'>;
}
declare module 'query-parse/test/test.js' {
  declare module.exports: $Exports<'query-parse/test/test'>;
}
