// flow-typed signature: 65b0f9b69517f33570276ea85e307333
// flow-typed version: <<STUB>>/react-addons-transition-group_v^15.6.2/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-addons-transition-group'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-addons-transition-group' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-addons-transition-group/index' {
  declare module.exports: $Exports<'react-addons-transition-group'>;
}
declare module 'react-addons-transition-group/index.js' {
  declare module.exports: $Exports<'react-addons-transition-group'>;
}
