// flow-typed signature: 666215a2fa392428580a6c84982a4a1d
// flow-typed version: <<STUB>>/react-fontawesome_v^1.3.1/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-fontawesome'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-fontawesome' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-fontawesome/examples/index' {
  declare module.exports: any;
}

declare module 'react-fontawesome/examples/webpack.config' {
  declare module.exports: any;
}

declare module 'react-fontawesome/lib/index' {
  declare module.exports: any;
}

declare module 'react-fontawesome/lib/screen-reader-styles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-fontawesome/examples/index.js' {
  declare module.exports: $Exports<'react-fontawesome/examples/index'>;
}
declare module 'react-fontawesome/examples/webpack.config.js' {
  declare module.exports: $Exports<'react-fontawesome/examples/webpack.config'>;
}
declare module 'react-fontawesome/lib/index.js' {
  declare module.exports: $Exports<'react-fontawesome/lib/index'>;
}
declare module 'react-fontawesome/lib/screen-reader-styles.js' {
  declare module.exports: $Exports<'react-fontawesome/lib/screen-reader-styles'>;
}
