// flow-typed signature: 628c9d338eccda5563e87146b82ee5e2
// flow-typed version: <<STUB>>/reconnectingwebsocket_v^1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reconnectingwebsocket'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reconnectingwebsocket' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reconnectingwebsocket/reconnecting-websocket' {
  declare module.exports: any;
}

declare module 'reconnectingwebsocket/reconnecting-websocket.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reconnectingwebsocket/reconnecting-websocket.js' {
  declare module.exports: $Exports<'reconnectingwebsocket/reconnecting-websocket'>;
}
declare module 'reconnectingwebsocket/reconnecting-websocket.min.js' {
  declare module.exports: $Exports<'reconnectingwebsocket/reconnecting-websocket.min'>;
}
