// flow-typed signature: ee0c8fa81db4c2e530295776e5aa4ee9
// flow-typed version: <<STUB>>/rich-text_v^3.0.1/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rich-text'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rich-text' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rich-text/lib/type' {
  declare module.exports: any;
}

declare module 'rich-text/test/fuzzer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rich-text/index' {
  declare module.exports: $Exports<'rich-text'>;
}
declare module 'rich-text/index.js' {
  declare module.exports: $Exports<'rich-text'>;
}
declare module 'rich-text/lib/type.js' {
  declare module.exports: $Exports<'rich-text/lib/type'>;
}
declare module 'rich-text/test/fuzzer.js' {
  declare module.exports: $Exports<'rich-text/test/fuzzer'>;
}
