// flow-typed signature: f54a68779761f6179946ad5b75d2b8e1
// flow-typed version: <<STUB>>/rws_v^0.0.1/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rws'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rws' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rws/dist/rws' {
  declare module.exports: any;
}

declare module 'rws/dist/rws.min' {
  declare module.exports: any;
}

declare module 'rws/examples/client' {
  declare module.exports: any;
}

declare module 'rws/examples/server' {
  declare module.exports: any;
}

declare module 'rws/lib/client' {
  declare module.exports: any;
}

declare module 'rws/lib/ReconnectingConnection' {
  declare module.exports: any;
}

declare module 'rws/lib/ReconnectingWebSocket' {
  declare module.exports: any;
}

declare module 'rws/lib/ReconnectingWebSocketServer' {
  declare module.exports: any;
}

declare module 'rws/lib/WebSocket' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rws/dist/rws.js' {
  declare module.exports: $Exports<'rws/dist/rws'>;
}
declare module 'rws/dist/rws.min.js' {
  declare module.exports: $Exports<'rws/dist/rws.min'>;
}
declare module 'rws/examples/client.js' {
  declare module.exports: $Exports<'rws/examples/client'>;
}
declare module 'rws/examples/server.js' {
  declare module.exports: $Exports<'rws/examples/server'>;
}
declare module 'rws/index' {
  declare module.exports: $Exports<'rws'>;
}
declare module 'rws/index.js' {
  declare module.exports: $Exports<'rws'>;
}
declare module 'rws/lib/client.js' {
  declare module.exports: $Exports<'rws/lib/client'>;
}
declare module 'rws/lib/ReconnectingConnection.js' {
  declare module.exports: $Exports<'rws/lib/ReconnectingConnection'>;
}
declare module 'rws/lib/ReconnectingWebSocket.js' {
  declare module.exports: $Exports<'rws/lib/ReconnectingWebSocket'>;
}
declare module 'rws/lib/ReconnectingWebSocketServer.js' {
  declare module.exports: $Exports<'rws/lib/ReconnectingWebSocketServer'>;
}
declare module 'rws/lib/WebSocket.js' {
  declare module.exports: $Exports<'rws/lib/WebSocket'>;
}
