// flow-typed signature: 1b4257bbd7cf90118e127813cc3639af
// flow-typed version: <<STUB>>/save-svg-as-png_v1.4.2/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'save-svg-as-png'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'save-svg-as-png' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'save-svg-as-png/saveSvgAsPng' {
  declare module.exports: any;
}

declare module 'save-svg-as-png/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'save-svg-as-png/index' {
  declare module.exports: $Exports<'save-svg-as-png'>;
}
declare module 'save-svg-as-png/index.js' {
  declare module.exports: $Exports<'save-svg-as-png'>;
}
declare module 'save-svg-as-png/saveSvgAsPng.js' {
  declare module.exports: $Exports<'save-svg-as-png/saveSvgAsPng'>;
}
declare module 'save-svg-as-png/test.js' {
  declare module.exports: $Exports<'save-svg-as-png/test'>;
}
