// flow-typed signature: 1f26f929c5f97653329f4ae385b4cff1
// flow-typed version: <<STUB>>/sharedb_v^1.0.0-beta.8/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sharedb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sharedb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sharedb/examples/counter/client' {
  declare module.exports: any;
}

declare module 'sharedb/examples/counter/server' {
  declare module.exports: any;
}

declare module 'sharedb/examples/leaderboard/client/Body' {
  declare module.exports: any;
}

declare module 'sharedb/examples/leaderboard/client/connection' {
  declare module.exports: any;
}

declare module 'sharedb/examples/leaderboard/client/index' {
  declare module.exports: any;
}

declare module 'sharedb/examples/leaderboard/client/Leaderboard' {
  declare module.exports: any;
}

declare module 'sharedb/examples/leaderboard/client/Player' {
  declare module.exports: any;
}

declare module 'sharedb/examples/leaderboard/client/PlayerList' {
  declare module.exports: any;
}

declare module 'sharedb/examples/leaderboard/client/PlayerSelector' {
  declare module.exports: any;
}

declare module 'sharedb/examples/leaderboard/server/index' {
  declare module.exports: any;
}

declare module 'sharedb/examples/rich-text/client' {
  declare module.exports: any;
}

declare module 'sharedb/examples/rich-text/server' {
  declare module.exports: any;
}

declare module 'sharedb/examples/textarea/client' {
  declare module.exports: any;
}

declare module 'sharedb/examples/textarea/server' {
  declare module.exports: any;
}

declare module 'sharedb/lib/agent' {
  declare module.exports: any;
}

declare module 'sharedb/lib/backend' {
  declare module.exports: any;
}

declare module 'sharedb/lib/client/connection' {
  declare module.exports: any;
}

declare module 'sharedb/lib/client/doc' {
  declare module.exports: any;
}

declare module 'sharedb/lib/client/index' {
  declare module.exports: any;
}

declare module 'sharedb/lib/client/query' {
  declare module.exports: any;
}

declare module 'sharedb/lib/db/index' {
  declare module.exports: any;
}

declare module 'sharedb/lib/db/memory' {
  declare module.exports: any;
}

declare module 'sharedb/lib/emitter' {
  declare module.exports: any;
}

declare module 'sharedb/lib/error' {
  declare module.exports: any;
}

declare module 'sharedb/lib/index' {
  declare module.exports: any;
}

declare module 'sharedb/lib/op-stream' {
  declare module.exports: any;
}

declare module 'sharedb/lib/ot' {
  declare module.exports: any;
}

declare module 'sharedb/lib/projections' {
  declare module.exports: any;
}

declare module 'sharedb/lib/pubsub/index' {
  declare module.exports: any;
}

declare module 'sharedb/lib/pubsub/memory' {
  declare module.exports: any;
}

declare module 'sharedb/lib/query-emitter' {
  declare module.exports: any;
}

declare module 'sharedb/lib/stream-socket' {
  declare module.exports: any;
}

declare module 'sharedb/lib/submit-request' {
  declare module.exports: any;
}

declare module 'sharedb/lib/types' {
  declare module.exports: any;
}

declare module 'sharedb/lib/util' {
  declare module.exports: any;
}

declare module 'sharedb/test/client/connection' {
  declare module.exports: any;
}

declare module 'sharedb/test/client/deserialized-type' {
  declare module.exports: any;
}

declare module 'sharedb/test/client/doc' {
  declare module.exports: any;
}

declare module 'sharedb/test/client/pending' {
  declare module.exports: any;
}

declare module 'sharedb/test/client/projections' {
  declare module.exports: any;
}

declare module 'sharedb/test/client/query-subscribe' {
  declare module.exports: any;
}

declare module 'sharedb/test/client/query' {
  declare module.exports: any;
}

declare module 'sharedb/test/client/submit' {
  declare module.exports: any;
}

declare module 'sharedb/test/client/subscribe' {
  declare module.exports: any;
}

declare module 'sharedb/test/db-memory' {
  declare module.exports: any;
}

declare module 'sharedb/test/db' {
  declare module.exports: any;
}

declare module 'sharedb/test/middleware' {
  declare module.exports: any;
}

declare module 'sharedb/test/ot' {
  declare module.exports: any;
}

declare module 'sharedb/test/projections' {
  declare module.exports: any;
}

declare module 'sharedb/test/pubsub-memory' {
  declare module.exports: any;
}

declare module 'sharedb/test/pubsub' {
  declare module.exports: any;
}

declare module 'sharedb/test/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sharedb/examples/counter/client.js' {
  declare module.exports: $Exports<'sharedb/examples/counter/client'>;
}
declare module 'sharedb/examples/counter/server.js' {
  declare module.exports: $Exports<'sharedb/examples/counter/server'>;
}
declare module 'sharedb/examples/leaderboard/client/Body.jsx' {
  declare module.exports: $Exports<'sharedb/examples/leaderboard/client/Body'>;
}
declare module 'sharedb/examples/leaderboard/client/connection.js' {
  declare module.exports: $Exports<'sharedb/examples/leaderboard/client/connection'>;
}
declare module 'sharedb/examples/leaderboard/client/index.jsx' {
  declare module.exports: $Exports<'sharedb/examples/leaderboard/client/index'>;
}
declare module 'sharedb/examples/leaderboard/client/Leaderboard.jsx' {
  declare module.exports: $Exports<'sharedb/examples/leaderboard/client/Leaderboard'>;
}
declare module 'sharedb/examples/leaderboard/client/Player.jsx' {
  declare module.exports: $Exports<'sharedb/examples/leaderboard/client/Player'>;
}
declare module 'sharedb/examples/leaderboard/client/PlayerList.jsx' {
  declare module.exports: $Exports<'sharedb/examples/leaderboard/client/PlayerList'>;
}
declare module 'sharedb/examples/leaderboard/client/PlayerSelector.jsx' {
  declare module.exports: $Exports<'sharedb/examples/leaderboard/client/PlayerSelector'>;
}
declare module 'sharedb/examples/leaderboard/server/index.js' {
  declare module.exports: $Exports<'sharedb/examples/leaderboard/server/index'>;
}
declare module 'sharedb/examples/rich-text/client.js' {
  declare module.exports: $Exports<'sharedb/examples/rich-text/client'>;
}
declare module 'sharedb/examples/rich-text/server.js' {
  declare module.exports: $Exports<'sharedb/examples/rich-text/server'>;
}
declare module 'sharedb/examples/textarea/client.js' {
  declare module.exports: $Exports<'sharedb/examples/textarea/client'>;
}
declare module 'sharedb/examples/textarea/server.js' {
  declare module.exports: $Exports<'sharedb/examples/textarea/server'>;
}
declare module 'sharedb/lib/agent.js' {
  declare module.exports: $Exports<'sharedb/lib/agent'>;
}
declare module 'sharedb/lib/backend.js' {
  declare module.exports: $Exports<'sharedb/lib/backend'>;
}
declare module 'sharedb/lib/client/connection.js' {
  declare module.exports: $Exports<'sharedb/lib/client/connection'>;
}
declare module 'sharedb/lib/client/doc.js' {
  declare module.exports: $Exports<'sharedb/lib/client/doc'>;
}
declare module 'sharedb/lib/client/index.js' {
  declare module.exports: $Exports<'sharedb/lib/client/index'>;
}
declare module 'sharedb/lib/client/query.js' {
  declare module.exports: $Exports<'sharedb/lib/client/query'>;
}
declare module 'sharedb/lib/db/index.js' {
  declare module.exports: $Exports<'sharedb/lib/db/index'>;
}
declare module 'sharedb/lib/db/memory.js' {
  declare module.exports: $Exports<'sharedb/lib/db/memory'>;
}
declare module 'sharedb/lib/emitter.js' {
  declare module.exports: $Exports<'sharedb/lib/emitter'>;
}
declare module 'sharedb/lib/error.js' {
  declare module.exports: $Exports<'sharedb/lib/error'>;
}
declare module 'sharedb/lib/index.js' {
  declare module.exports: $Exports<'sharedb/lib/index'>;
}
declare module 'sharedb/lib/op-stream.js' {
  declare module.exports: $Exports<'sharedb/lib/op-stream'>;
}
declare module 'sharedb/lib/ot.js' {
  declare module.exports: $Exports<'sharedb/lib/ot'>;
}
declare module 'sharedb/lib/projections.js' {
  declare module.exports: $Exports<'sharedb/lib/projections'>;
}
declare module 'sharedb/lib/pubsub/index.js' {
  declare module.exports: $Exports<'sharedb/lib/pubsub/index'>;
}
declare module 'sharedb/lib/pubsub/memory.js' {
  declare module.exports: $Exports<'sharedb/lib/pubsub/memory'>;
}
declare module 'sharedb/lib/query-emitter.js' {
  declare module.exports: $Exports<'sharedb/lib/query-emitter'>;
}
declare module 'sharedb/lib/stream-socket.js' {
  declare module.exports: $Exports<'sharedb/lib/stream-socket'>;
}
declare module 'sharedb/lib/submit-request.js' {
  declare module.exports: $Exports<'sharedb/lib/submit-request'>;
}
declare module 'sharedb/lib/types.js' {
  declare module.exports: $Exports<'sharedb/lib/types'>;
}
declare module 'sharedb/lib/util.js' {
  declare module.exports: $Exports<'sharedb/lib/util'>;
}
declare module 'sharedb/test/client/connection.js' {
  declare module.exports: $Exports<'sharedb/test/client/connection'>;
}
declare module 'sharedb/test/client/deserialized-type.js' {
  declare module.exports: $Exports<'sharedb/test/client/deserialized-type'>;
}
declare module 'sharedb/test/client/doc.js' {
  declare module.exports: $Exports<'sharedb/test/client/doc'>;
}
declare module 'sharedb/test/client/pending.js' {
  declare module.exports: $Exports<'sharedb/test/client/pending'>;
}
declare module 'sharedb/test/client/projections.js' {
  declare module.exports: $Exports<'sharedb/test/client/projections'>;
}
declare module 'sharedb/test/client/query-subscribe.js' {
  declare module.exports: $Exports<'sharedb/test/client/query-subscribe'>;
}
declare module 'sharedb/test/client/query.js' {
  declare module.exports: $Exports<'sharedb/test/client/query'>;
}
declare module 'sharedb/test/client/submit.js' {
  declare module.exports: $Exports<'sharedb/test/client/submit'>;
}
declare module 'sharedb/test/client/subscribe.js' {
  declare module.exports: $Exports<'sharedb/test/client/subscribe'>;
}
declare module 'sharedb/test/db-memory.js' {
  declare module.exports: $Exports<'sharedb/test/db-memory'>;
}
declare module 'sharedb/test/db.js' {
  declare module.exports: $Exports<'sharedb/test/db'>;
}
declare module 'sharedb/test/middleware.js' {
  declare module.exports: $Exports<'sharedb/test/middleware'>;
}
declare module 'sharedb/test/ot.js' {
  declare module.exports: $Exports<'sharedb/test/ot'>;
}
declare module 'sharedb/test/projections.js' {
  declare module.exports: $Exports<'sharedb/test/projections'>;
}
declare module 'sharedb/test/pubsub-memory.js' {
  declare module.exports: $Exports<'sharedb/test/pubsub-memory'>;
}
declare module 'sharedb/test/pubsub.js' {
  declare module.exports: $Exports<'sharedb/test/pubsub'>;
}
declare module 'sharedb/test/util.js' {
  declare module.exports: $Exports<'sharedb/test/util'>;
}
