// flow-typed signature: 37852bb8fdfaa9edbd542ab0e3d01e92
// flow-typed version: <<STUB>>/sharedb-mongo_v^1.0.0-beta.4/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sharedb-mongo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sharedb-mongo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sharedb-mongo/test/test_mongo' {
  declare module.exports: any;
}

declare module 'sharedb-mongo/test/test_skip_poll' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sharedb-mongo/index' {
  declare module.exports: $Exports<'sharedb-mongo'>;
}
declare module 'sharedb-mongo/index.js' {
  declare module.exports: $Exports<'sharedb-mongo'>;
}
declare module 'sharedb-mongo/test/test_mongo.js' {
  declare module.exports: $Exports<'sharedb-mongo/test/test_mongo'>;
}
declare module 'sharedb-mongo/test/test_skip_poll.js' {
  declare module.exports: $Exports<'sharedb-mongo/test/test_skip_poll'>;
}
