// flow-typed signature: 06d3b868685fc1457246151cb73e1fc7
// flow-typed version: <<STUB>>/sharedb-redis-pubsub_v^1.0.0-beta.1/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sharedb-redis-pubsub'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sharedb-redis-pubsub' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sharedb-redis-pubsub/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sharedb-redis-pubsub/index' {
  declare module.exports: $Exports<'sharedb-redis-pubsub'>;
}
declare module 'sharedb-redis-pubsub/index.js' {
  declare module.exports: $Exports<'sharedb-redis-pubsub'>;
}
declare module 'sharedb-redis-pubsub/test/test.js' {
  declare module.exports: $Exports<'sharedb-redis-pubsub/test/test'>;
}
