// flow-typed signature: 593b219911dfd634b1f72c6d1ac809ce
// flow-typed version: <<STUB>>/websocket-json-stream_v0.0.3/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'websocket-json-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'websocket-json-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'websocket-json-stream/index' {
  declare module.exports: $Exports<'websocket-json-stream'>;
}
declare module 'websocket-json-stream/index.js' {
  declare module.exports: $Exports<'websocket-json-stream'>;
}
