// flow-typed signature: a1c30f6256fe4dd86fc3533efdb32e11
// flow-typed version: <<STUB>>/@babel/plugin-proposal-decorators_v^7.0.0-beta.39/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-proposal-decorators'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-proposal-decorators' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-proposal-decorators/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-proposal-decorators/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-decorators/lib/index'>;
}
