// flow-typed signature: fcf1cce7218e073b329e132de08c7b98
// flow-typed version: <<STUB>>/@babel/plugin-transform-flow-comments_v7.0.0-beta.46/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-transform-flow-comments'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-transform-flow-comments' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-transform-flow-comments/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-transform-flow-comments/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-flow-comments/lib/index'>;
}
