mv op-aggregate/src/* op-aggregate/
rm -rf op-aggregate/src
mv op-aggregate-groups/src/* op-aggregate-groups/
rm -rf op-aggregate-groups/src
mv op-aggregate-p2/src/* op-aggregate-p2/
rm -rf op-aggregate-p2/src
mv op-aggregate-spreadsheet/src/* op-aggregate-spreadsheet/
rm -rf op-aggregate-spreadsheet/src
mv op-argue/src/* op-argue/
rm -rf op-argue/src
mv op-argue-constraint/src/* op-argue-constraint/
rm -rf op-argue-constraint/src
mv op-check-concepts/src/* op-check-concepts/
rm -rf op-check-concepts/src
mv op-combine-groups/src/* op-combine-groups/
rm -rf op-combine-groups/src
mv op-control-group/src/* op-control-group/
rm -rf op-control-group/src
mv op-create-groups/src/* op-create-groups/
rm -rf op-create-groups/src
mv op-cs211-ranking/src/* op-cs211-ranking/
rm -rf op-cs211-ranking/src
mv op-dataset/src/* op-dataset/
rm -rf op-dataset/src
mv op-distrib-round-robin/src/* op-distrib-round-robin/
rm -rf op-distrib-round-robin/src
mv op-distribute/src/* op-distribute/
rm -rf op-distribute/src
mv op-distribute-category/src/* op-distribute-category/
rm -rf op-distribute-category/src
mv op-filter/src/* op-filter/
rm -rf op-filter/src
mv op-group-identical/src/* op-group-identical/
rm -rf op-group-identical/src
mv op-hypothesis/src/* op-hypothesis/
rm -rf op-hypothesis/src
mv op-jigsaw/src/* op-jigsaw/
rm -rf op-jigsaw/src
mv op-map-external/src/* op-map-external/
rm -rf op-map-external/src
mv op-merge/src/* op-merge/
rm -rf op-merge/src
mv op-performance-select/src/* op-performance-select/
rm -rf op-performance-select/src
mv op-prox/src/* op-prox/
rm -rf op-prox/src
mv op-returnReviews/src/* op-returnReviews/
rm -rf op-returnReviews/src
mv op-richtext-diff/src/* op-richtext-diff/
rm -rf op-richtext-diff/src
mv op-rss/src/* op-rss/
rm -rf op-rss/src
mv op-select-best/src/* op-select-best/
rm -rf op-select-best/src
mv op-social-category/src/* op-social-category/
rm -rf op-social-category/src
mv op-social-config/src/* op-social-config/
rm -rf op-social-config/src
mv op-social-name/src/* op-social-name/
rm -rf op-social-name/src
mv op-twitter/src/* op-twitter/
rm -rf op-twitter/src
mv op-wrap-peer-review/src/* op-wrap-peer-review/
rm -rf op-wrap-peer-review/src
mv op-xy-distance/src/* op-xy-distance/
rm -rf op-xy-distance/src
