// flow-typed signature: c3c5fcafd61aecd98145522723ba61d8
// flow-typed version: <<STUB>>/@material-ui/codemod_v^1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/codemod'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/codemod' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/codemod/lib/v0.15.0/import-path' {
  declare module.exports: any;
}

declare module '@material-ui/codemod/lib/v1.0.0/color-imports' {
  declare module.exports: any;
}

declare module '@material-ui/codemod/lib/v1.0.0/import-path' {
  declare module.exports: any;
}

declare module '@material-ui/codemod/lib/v1.0.0/svg-icon-imports' {
  declare module.exports: any;
}

declare module '@material-ui/codemod/src/v0.15.0/import-path' {
  declare module.exports: any;
}

declare module '@material-ui/codemod/src/v0.15.0/import-path.test/actual' {
  declare module.exports: any;
}

declare module '@material-ui/codemod/src/v0.15.0/import-path.test/expected' {
  declare module.exports: any;
}

declare module '@material-ui/codemod/src/v1.0.0/color-imports' {
  declare module.exports: any;
}

declare module '@material-ui/codemod/src/v1.0.0/color-imports.test/actual' {
  declare module.exports: any;
}

declare module '@material-ui/codemod/src/v1.0.0/color-imports.test/expected' {
  declare module.exports: any;
}

declare module '@material-ui/codemod/src/v1.0.0/import-path' {
  declare module.exports: any;
}

declare module '@material-ui/codemod/src/v1.0.0/import-path.test/actual' {
  declare module.exports: any;
}

declare module '@material-ui/codemod/src/v1.0.0/import-path.test/expected' {
  declare module.exports: any;
}

declare module '@material-ui/codemod/src/v1.0.0/svg-icon-imports' {
  declare module.exports: any;
}

declare module '@material-ui/codemod/src/v1.0.0/svg-icon-imports.test/actual' {
  declare module.exports: any;
}

declare module '@material-ui/codemod/src/v1.0.0/svg-icon-imports.test/expected' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/codemod/lib/v0.15.0/import-path.js' {
  declare module.exports: $Exports<'@material-ui/codemod/lib/v0.15.0/import-path'>;
}
declare module '@material-ui/codemod/lib/v1.0.0/color-imports.js' {
  declare module.exports: $Exports<'@material-ui/codemod/lib/v1.0.0/color-imports'>;
}
declare module '@material-ui/codemod/lib/v1.0.0/import-path.js' {
  declare module.exports: $Exports<'@material-ui/codemod/lib/v1.0.0/import-path'>;
}
declare module '@material-ui/codemod/lib/v1.0.0/svg-icon-imports.js' {
  declare module.exports: $Exports<'@material-ui/codemod/lib/v1.0.0/svg-icon-imports'>;
}
declare module '@material-ui/codemod/src/v0.15.0/import-path.js' {
  declare module.exports: $Exports<'@material-ui/codemod/src/v0.15.0/import-path'>;
}
declare module '@material-ui/codemod/src/v0.15.0/import-path.test/actual.js' {
  declare module.exports: $Exports<'@material-ui/codemod/src/v0.15.0/import-path.test/actual'>;
}
declare module '@material-ui/codemod/src/v0.15.0/import-path.test/expected.js' {
  declare module.exports: $Exports<'@material-ui/codemod/src/v0.15.0/import-path.test/expected'>;
}
declare module '@material-ui/codemod/src/v1.0.0/color-imports.js' {
  declare module.exports: $Exports<'@material-ui/codemod/src/v1.0.0/color-imports'>;
}
declare module '@material-ui/codemod/src/v1.0.0/color-imports.test/actual.js' {
  declare module.exports: $Exports<'@material-ui/codemod/src/v1.0.0/color-imports.test/actual'>;
}
declare module '@material-ui/codemod/src/v1.0.0/color-imports.test/expected.js' {
  declare module.exports: $Exports<'@material-ui/codemod/src/v1.0.0/color-imports.test/expected'>;
}
declare module '@material-ui/codemod/src/v1.0.0/import-path.js' {
  declare module.exports: $Exports<'@material-ui/codemod/src/v1.0.0/import-path'>;
}
declare module '@material-ui/codemod/src/v1.0.0/import-path.test/actual.js' {
  declare module.exports: $Exports<'@material-ui/codemod/src/v1.0.0/import-path.test/actual'>;
}
declare module '@material-ui/codemod/src/v1.0.0/import-path.test/expected.js' {
  declare module.exports: $Exports<'@material-ui/codemod/src/v1.0.0/import-path.test/expected'>;
}
declare module '@material-ui/codemod/src/v1.0.0/svg-icon-imports.js' {
  declare module.exports: $Exports<'@material-ui/codemod/src/v1.0.0/svg-icon-imports'>;
}
declare module '@material-ui/codemod/src/v1.0.0/svg-icon-imports.test/actual.js' {
  declare module.exports: $Exports<'@material-ui/codemod/src/v1.0.0/svg-icon-imports.test/actual'>;
}
declare module '@material-ui/codemod/src/v1.0.0/svg-icon-imports.test/expected.js' {
  declare module.exports: $Exports<'@material-ui/codemod/src/v1.0.0/svg-icon-imports.test/expected'>;
}
