mv ./ac-autocode/src/ActivityRunner/Editor.jsx ./ac-autocode/src/ActivityRunner/Editor.js
mv ./ac-autocode/src/ActivityRunner/Header.jsx ./ac-autocode/src/ActivityRunner/Header.js
mv ./ac-autocode/src/ActivityRunner/MakeRunCode/Javascript.jsx ./ac-autocode/src/ActivityRunner/MakeRunCode/Javascript.js
mv ./ac-autocode/src/ActivityRunner/MakeRunCode/Python.jsx ./ac-autocode/src/ActivityRunner/MakeRunCode/Python.js
mv ./ac-autocode/src/ActivityRunner/Test.jsx ./ac-autocode/src/ActivityRunner/Test.js
mv ./ac-autocode/src/ActivityRunner/TestPanel.jsx ./ac-autocode/src/ActivityRunner/TestPanel.js
mv ./ac-autocode/src/Dashboard.jsx ./ac-autocode/src/Dashboard.js
mv ./ac-brainstorm/src/ActivityRunner.jsx ./ac-brainstorm/src/ActivityRunner.js
mv ./ac-brainstorm/src/Dashboard.jsx ./ac-brainstorm/src/Dashboard.js
mv ./ac-chat/src/Chat.jsx ./ac-chat/src/Chat.js
mv ./ac-chat/src/Dashboard.jsx ./ac-chat/src/Dashboard.js
mv ./ac-chat/src/TextInput.jsx ./ac-chat/src/TextInput.js
mv ./ac-classifier/src/Classifier.jsx ./ac-classifier/src/Classifier.js
mv ./ac-classifier/src/components/ObjectList.jsx ./ac-classifier/src/components/ObjectList.js
mv ./ac-classifier/src/components/ObjectPanel.jsx ./ac-classifier/src/components/ObjectPanel.js
mv ./ac-classifier/src/components/ShortcutPanel.jsx ./ac-classifier/src/components/ShortcutPanel.js
mv ./ac-dual/src/ActivityRunner.jsx ./ac-dual/src/ActivityRunner.js
mv ./ac-dual/src/ActivityUtils.jsx ./ac-dual/src/ActivityUtils.js
mv ./ac-dual/src/Dashboard.jsx ./ac-dual/src/Dashboard.js
mv ./ac-dual/src/Game.jsx ./ac-dual/src/Game.js
mv ./ac-dual/src/Symmetry.jsx ./ac-dual/src/Symmetry.js
mv ./ac-image/src/ActivityRunner.jsx ./ac-image/src/ActivityRunner.js
mv ./ac-image/src/components/CategoryBox.jsx ./ac-image/src/components/CategoryBox.js
mv ./ac-image/src/components/CenteredImg.jsx ./ac-image/src/components/CenteredImg.js
mv ./ac-image/src/components/ImageBox.jsx ./ac-image/src/components/ImageBox.js
mv ./ac-image/src/components/ThumbList.jsx ./ac-image/src/components/ThumbList.js
mv ./ac-image/src/components/TopBar.jsx ./ac-image/src/components/TopBar.js
mv ./ac-image/src/components/UploadBar.jsx ./ac-image/src/components/UploadBar.js
mv ./ac-image/src/components/UploadDragDrop.jsx ./ac-image/src/components/UploadDragDrop.js
mv ./ac-image/src/components/WebcamInterface.jsx ./ac-image/src/components/WebcamInterface.js
mv ./ac-image/src/components/ZoomView.jsx ./ac-image/src/components/ZoomView.js
mv ./ac-image/src/Dashboard.jsx ./ac-image/src/Dashboard.js
mv ./ac-induction/src/ActivityRunner.jsx ./ac-induction/src/ActivityRunner.js
mv ./ac-induction/src/Dashboard.jsx ./ac-induction/src/Dashboard.js
mv ./ac-induction/src/DashboardComponents.jsx ./ac-induction/src/DashboardComponents.js
mv ./ac-induction/src/Definition.jsx ./ac-induction/src/Definition.js
mv ./ac-induction/src/End.jsx ./ac-induction/src/End.js
mv ./ac-induction/src/Examples.jsx ./ac-induction/src/Examples.js
mv ./ac-induction/src/ImgBis.jsx ./ac-induction/src/ImgBis.js
mv ./ac-induction/src/NavigationBar.jsx ./ac-induction/src/NavigationBar.js
mv ./ac-induction/src/Presentation.jsx ./ac-induction/src/Presentation.js
mv ./ac-induction/src/TestPart/ModalSubmit.jsx ./ac-induction/src/TestPart/ModalSubmit.js
mv ./ac-induction/src/TestPart/ResponsePanel.jsx ./ac-induction/src/TestPart/ResponsePanel.js
mv ./ac-induction/src/TestPart/Switch.jsx ./ac-induction/src/TestPart/Switch.js
mv ./ac-induction/src/TestPart/Test.jsx ./ac-induction/src/TestPart/Test.js
mv ./ac-monty/src/ActivityRunner.jsx ./ac-monty/src/ActivityRunner.js
mv ./ac-prez/src/AnnotationLayer.jsx ./ac-prez/src/AnnotationLayer.js
mv ./ac-prez/src/PDF.jsx ./ac-prez/src/PDF.js
mv ./ac-prez/src/Prez.jsx ./ac-prez/src/Prez.js
mv ./ac-prox/src/ActivityRunner.jsx ./ac-prox/src/ActivityRunner.js
mv ./ac-prox/src/GroupPanel.jsx ./ac-prox/src/GroupPanel.js
mv ./ac-prox/src/NoGroupPanel.jsx ./ac-prox/src/NoGroupPanel.js
mv ./ac-quiz/src/ActivityRunner/Justification.jsx ./ac-quiz/src/ActivityRunner/Justification.js
mv ./ac-quiz/src/ActivityRunner/Question.jsx ./ac-quiz/src/ActivityRunner/Question.js
mv ./ac-quiz/src/ActivityRunner/Quiz.jsx ./ac-quiz/src/ActivityRunner/Quiz.js
mv ./ac-quiz/src/ActivityRunner/Widget.jsx ./ac-quiz/src/ActivityRunner/Widget.js
mv ./ac-quiz/src/Dashboard/JustificationDashboard.jsx ./ac-quiz/src/Dashboard/JustificationDashboard.js
mv ./ac-ranking/src/ActivityRunner/AddAnswer.jsx ./ac-ranking/src/ActivityRunner/AddAnswer.js
mv ./ac-ranking/src/ActivityRunner/Answer.jsx ./ac-ranking/src/ActivityRunner/Answer.js
mv ./ac-ranking/src/ActivityRunner/AnswerList.jsx ./ac-ranking/src/ActivityRunner/AnswerList.js
mv ./ac-ranking/src/ActivityRunner/Justification.jsx ./ac-ranking/src/ActivityRunner/Justification.js
mv ./ac-ranking/src/Dashboard.jsx ./ac-ranking/src/Dashboard.js
mv ./ac-stroop/src/ActivityRunner.jsx ./ac-stroop/src/ActivityRunner.js
mv ./ac-stroop/src/Dashboard.jsx ./ac-stroop/src/Dashboard.js
mv ./ac-timedQuiz/src/ActivityRunner.jsx ./ac-timedQuiz/src/ActivityRunner.js
mv ./ac-timedQuiz/src/Dashboard.jsx ./ac-timedQuiz/src/Dashboard.js
mv ./ac-train/src/ActivityRunner.jsx ./ac-train/src/ActivityRunner.js
mv ./ac-train/src/ActivityUtils.jsx ./ac-train/src/ActivityUtils.js
mv ./ac-train/src/Dashboards/index.jsx ./ac-train/src/Dashboards/index.js
mv ./ac-train/src/Dashboards/MeanPerInterface.jsx ./ac-train/src/Dashboards/MeanPerInterface.js
mv ./ac-train/src/Dashboards/MeanPerTryForEachInterface.jsx ./ac-train/src/Dashboards/MeanPerTryForEachInterface.js
mv ./ac-train/src/Dashboards/MeanThroughOutStudy.jsx ./ac-train/src/Dashboards/MeanThroughOutStudy.js
mv ./ac-train/src/Guidelines.jsx ./ac-train/src/Guidelines.js
mv ./ac-train/src/Interface.jsx ./ac-train/src/Interface.js
mv ./ac-train/src/Interfaces/Actions.jsx ./ac-train/src/Interfaces/Actions.js
mv ./ac-train/src/Interfaces/Command.jsx ./ac-train/src/Interfaces/Command.js
mv ./ac-train/src/Interfaces/DragDrop/Box.jsx ./ac-train/src/Interfaces/DragDrop/Box.js
mv ./ac-train/src/Interfaces/DragDrop/DropElements.jsx ./ac-train/src/Interfaces/DragDrop/DropElements.js
mv ./ac-train/src/Interfaces/DragDrop/index.jsx ./ac-train/src/Interfaces/DragDrop/index.js
mv ./ac-train/src/Interfaces/Form.jsx ./ac-train/src/Interfaces/Form.js
mv ./ac-train/src/Interfaces/Help.jsx ./ac-train/src/Interfaces/Help.js
mv ./ac-train/src/Interfaces/MapInterface/FromToInputs.jsx ./ac-train/src/Interfaces/MapInterface/FromToInputs.js
mv ./ac-train/src/Interfaces/MapInterface/index.jsx ./ac-train/src/Interfaces/MapInterface/index.js
mv ./ac-train/src/Interfaces/MapInterface/RadioGroupElements.jsx ./ac-train/src/Interfaces/MapInterface/RadioGroupElements.js
mv ./ac-train/src/Interfaces/MapInterface/SwissMap.jsx ./ac-train/src/Interfaces/MapInterface/SwissMap.js
mv ./ac-train/src/TicketStatus.jsx ./ac-train/src/TicketStatus.js
mv ./ac-train/src/Timer.jsx ./ac-train/src/Timer.js
mv ./ac-uploader/src/ActivityRunner.jsx ./ac-uploader/src/ActivityRunner.js
mv ./ac-uploader/src/List.jsx ./ac-uploader/src/List.js
mv ./ac-uploader/src/Presentation.jsx ./ac-uploader/src/Presentation.js
mv ./ac-uploader/src/UploadPanel.jsx ./ac-uploader/src/UploadPanel.js
mv ./ac-videochat/src/ActivityRunner/Header.jsx ./ac-videochat/src/ActivityRunner/Header.js
mv ./ac-videochat/src/ActivityRunner/Video.jsx ./ac-videochat/src/ActivityRunner/Video.js
mv ./ac-videochat/src/ActivityRunner/VideoLayout.jsx ./ac-videochat/src/ActivityRunner/VideoLayout.js
mv ./ac-videochat/src/Dashboard.jsx ./ac-videochat/src/Dashboard.js
